// ============================================================
// CODEX ATLAS — INVESTIGATION V2 VIEW
// ============================================================
//
// Filed 2026-06-10. The consumer-facing findings section: every
// documented cross-tradition finding the investigation has produced,
// in one searchable, filterable surface. Brings back the IDEA of the
// prototype's observations / patterns / findings tabs — none of its
// chrome, class names, or aesthetic (V2 tokens throughout).
//
// Data source: src/data/investigation-index.json, generated by
// scripts/build_investigation_index.py (read-only harvest of
// observations.js + patterns.js + chains.js + the 00_meta findings
// corpus + every node-level findings section in the vault).
// Loading: window.INVESTIGATION_INDEX global if present (integrator
// may pre-load it), otherwise fetched on first render and cached in
// module state for later re-mounts.
//
// Consumer language: the index generator already scrubs internal
// jargon; this module renders titles/summaries/bodies verbatim and
// never introduces internal vocabulary of its own.
//
// Styles: this module injects a <style id="investigation-style">
// block (it may not edit src/styles/app.css). The integrator can
// move that block into app.css verbatim and delete the injection.
//
// Boundary contract (public API), mirroring maps.js / alphabets.js:
//   window._investigationView = { render(pane), unmount() }
//
// VIEWS.investigation in src/js/app.js delegates to render(pane).
// ============================================================
(function () {
  'use strict';

  var _pane = null;
  var _loadToken = 0;
  var _data = null;            // cached parsed index ({findings, categories, …})
  var _state = {
    cat: 'All',
    query: '',
    shown: 0,                  // how many cards are currently rendered
  };
  var CHUNK = 150;

  // ── category presentation ─────────────────────────────────────
  var CAT_COLOR = {
    'Transmission':             '90,172,168',   // teal
    'Convergence':              '212,165,90',   // gold
    'Inversion':                '196,74,90',    // red
    'Conclusion':               '122,184,204',  // sky
    'Hypothesis':               '204,148,102',  // copper
    'Anomaly':                  '204,106,58',   // deep orange
    'Discovery':                '122,204,154',  // green
    'Open question':            '176,154,216',  // violet
    'Method':                   '138,147,165',  // slate
    'Cross-tradition parallel': '154,167,184',  // steel
  };
  var CAT_HINT = {
    'Transmission': 'an idea, symbol, or practice that demonstrably travelled from one tradition to another',
    'Convergence': 'traditions with no documented contact arriving at the same structure',
    'Inversion': 'a symbol kept but its meaning flipped by the receiving tradition',
    'Conclusion': 'supported by multiple independent confirmations',
    'Hypothesis': 'a testable claim the evidence points toward',
    'Anomaly': 'something that breaks the expected pattern',
    'Discovery': 'manuscript, textual, and dating discoveries',
    'Open question': 'documented but unsolved',
    'Method': 'how this investigation reads the record',
    'Cross-tradition parallel': 'documented links recorded on individual Atlas entries',
  };

  function catRGB(cat) { return CAT_COLOR[cat] || CAT_COLOR['Cross-tradition parallel']; }

  // ── utilities ─────────────────────────────────────────────────
  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  var _nodesById = null;
  function nodesById() {
    if (_nodesById) return _nodesById;
    _nodesById = {};
    var nodes = (window.VAULT_DATA && window.VAULT_DATA.nodes) || [];
    for (var i = 0; i < nodes.length; i++) _nodesById[nodes[i].id] = nodes[i];
    return _nodesById;
  }

  // markdown-lite (bold / italic / inline code), input is escaped first
  function fmtInline(raw) {
    var s = esc(raw);
    s = s.replace(/\*\*([^*]+)\*\*/g, '<b>$1</b>');
    s = s.replace(/(^|[\s(>—–·])\*([^*\n]+)\*(?=$|[\s).,;:!?—–])/g, '$1<i>$2</i>');
    s = s.replace(/`([^`]+)`/g, '<code>$1</code>');
    return s;
  }

  // block-level markdown-lite for finding bodies:
  // paragraphs, "- " bullets, | tables |, residual #### headings.
  function fmtBody(text) {
    var lines = String(text || '').split('\n');
    var html = [];
    var para = [], list = [], table = [];

    function flushPara() {
      if (para.length) { html.push('<p>' + fmtInline(para.join(' ')) + '</p>'); para = []; }
    }
    function flushList() {
      if (list.length) {
        html.push('<ul>' + list.map(function (li) { return '<li>' + fmtInline(li) + '</li>'; }).join('') + '</ul>');
        list = [];
      }
    }
    function flushTable() {
      if (!table.length) { return; }
      var rows = table.map(function (cells, ri) {
        var tag = ri === 0 ? 'th' : 'td';
        return '<tr>' + cells.map(function (c) { return '<' + tag + '>' + fmtInline(c) + '</' + tag + '>'; }).join('') + '</tr>';
      });
      html.push('<div class="investigation-tablewrap"><table>' + rows.join('') + '</table></div>');
      table = [];
    }
    function flushAll() { flushPara(); flushList(); flushTable(); }

    for (var i = 0; i < lines.length; i++) {
      var line = lines[i];
      var t = line.trim();
      if (!t) { flushAll(); continue; }
      if (t.charAt(0) === '|') {
        flushPara(); flushList();
        if (/^\|[\s\-:|]+\|?$/.test(t)) continue;            // separator row
        var cells = t.replace(/^\||\|$/g, '').split('|').map(function (c) { return c.trim(); });
        table.push(cells);
        continue;
      }
      flushTable();
      var li = t.match(/^[-•*]\s+(.+)$/);
      if (li) { flushPara(); list.push(li[1]); continue; }
      var hd = t.match(/^#{1,6}\s+(.+)$/);
      if (hd) { flushAll(); html.push('<div class="investigation-bodyhead">' + fmtInline(hd[1]) + '</div>'); continue; }
      flushList();
      para.push(t);
    }
    flushAll();
    return html.join('');
  }

  // ── data loading ──────────────────────────────────────────────
  function normalize(raw) {
    if (!raw) return null;
    var findings = Array.isArray(raw) ? raw : (raw.findings || []);
    if (!findings.length) return null;
    var categories = (!Array.isArray(raw) && raw.categories) ? raw.categories.slice() : [];
    if (!categories.length) {
      var seen = {};
      findings.forEach(function (f) { if (f.category && !seen[f.category]) { seen[f.category] = 1; categories.push(f.category); } });
    }
    var rank = {};
    categories.forEach(function (c, i) { rank[c] = i; });
    findings.forEach(function (f) {
      f._hay = (
        (f.title || '') + ' ' + (f.summary || '') + ' ' + (f.body || '') + ' ' +
        (f.tags || []).join(' ') + ' ' + (f.sources || []).join(' ')
      ).toLowerCase();
    });
    findings.sort(function (a, b) {
      var ra = rank[a.category] != null ? rank[a.category] : 99;
      var rb = rank[b.category] != null ? rank[b.category] : 99;
      if (ra !== rb) return ra - rb;
      return (a.title || '').localeCompare(b.title || '');
    });
    return { findings: findings, categories: categories };
  }

  function load() {
    if (_data) return Promise.resolve(_data);
    var fromGlobal = normalize(window.INVESTIGATION_INDEX);
    if (fromGlobal) { _data = fromGlobal; return Promise.resolve(_data); }
    return fetch('src/data/investigation-index.json?_=' + Date.now(), { cache: 'no-store' })
      .then(function (r) {
        if (!r.ok) throw new Error('HTTP ' + r.status);
        return r.json();
      })
      .then(function (json) {
        _data = normalize(json);
        if (!_data) throw new Error('index is empty');
        return _data;
      });
  }

  // ── filtering ─────────────────────────────────────────────────
  function filtered() {
    var list = _data.findings;
    var cat = _state.cat;
    var q = _state.query.trim().toLowerCase();
    if (cat !== 'All') list = list.filter(function (f) { return f.category === cat; });
    if (q) {
      var terms = q.split(/\s+/);
      list = list.filter(function (f) {
        for (var i = 0; i < terms.length; i++) {
          if (f._hay.indexOf(terms[i]) === -1) return false;
        }
        return true;
      });
    }
    return list;
  }

  // ── rendering ─────────────────────────────────────────────────
  function badge(cat) {
    var rgb = catRGB(cat);
    return '<span class="investigation-badge" title="' + esc(CAT_HINT[cat] || '') + '" ' +
      'style="background:rgba(' + rgb + ',0.12);border-color:rgba(' + rgb + ',0.45);color:rgb(' + rgb + ')">' +
      esc(cat) + '</span>';
  }

  function sourceChips(f) {
    var byId = nodesById();
    var srcs = f.sources || [];
    if (!srcs.length) return '';
    var chips = srcs.map(function (id) {
      var n = byId[id];
      if (n) {
        return '<button type="button" class="investigation-src" data-id="' + esc(id) + '">' + esc(n.title || id) + '</button>';
      }
      return '<span class="investigation-src investigation-src--miss" title="not yet in the Atlas">' + esc(id) + '</span>';
    });
    return '<div class="investigation-srcs"><span class="investigation-srcs-label">evidence</span>' + chips.join('') + '</div>';
  }

  function card(f) {
    var hasBody = !!(f.body && f.body.trim() && f.body.trim() !== (f.summary || '').trim());
    return '<article class="investigation-card" data-fid="' + esc(f.id) + '">' +
      '<div class="investigation-card-head">' + badge(f.category) +
        '<h3 class="investigation-card-title">' + esc(f.title) + '</h3>' +
      '</div>' +
      (f.summary ? '<p class="investigation-card-summary">' + esc(f.summary) + '</p>' : '') +
      (hasBody
        ? '<details class="investigation-card-more">' +
            '<summary>full note</summary>' +
            '<div class="investigation-card-body" data-raw="1"></div>' +
          '</details>'
        : '') +
      sourceChips(f) +
    '</article>';
  }

  function renderChips() {
    var counts = { All: _data.findings.length };
    _data.findings.forEach(function (f) { counts[f.category] = (counts[f.category] || 0) + 1; });
    var cats = ['All'].concat(_data.categories.filter(function (c) { return counts[c]; }));
    return cats.map(function (c) {
      var active = _state.cat === c ? ' is-active' : '';
      var rgb = c === 'All' ? '212,165,90' : catRGB(c);
      return '<button type="button" class="investigation-chip' + active + '" data-cat="' + esc(c) + '" ' +
        'style="--inv-chip:' + rgb + '">' + esc(c) +
        '<span class="investigation-chip-n">' + counts[c] + '</span></button>';
    }).join('');
  }

  function renderList() {
    if (!_pane) return;
    var listEl = _pane.querySelector('#investigation-list');
    var metaEl = _pane.querySelector('#investigation-meta');
    if (!listEl) return;
    var list = filtered();
    _state.shown = Math.min(Math.max(_state.shown, CHUNK), list.length);
    var slice = list.slice(0, _state.shown);
    listEl.innerHTML = slice.map(card).join('') +
      (list.length > _state.shown
        ? '<button type="button" class="investigation-more-btn" id="investigation-more">show more · ' +
          (list.length - _state.shown) + ' remaining</button>'
        : '');
    if (metaEl) {
      var total = _data.findings.length;
      metaEl.textContent = (list.length === total)
        ? total + ' findings · ' + _data.categories.length + ' categories'
        : list.length + ' of ' + total + ' findings';
    }
  }

  function expandBody(detailsEl) {
    var holder = detailsEl.querySelector('.investigation-card-body[data-raw]');
    if (!holder) return;
    holder.removeAttribute('data-raw');
    var cardEl = detailsEl.closest('.investigation-card');
    var fid = cardEl && cardEl.getAttribute('data-fid');
    if (!fid || !_data) return;
    for (var i = 0; i < _data.findings.length; i++) {
      if (_data.findings[i].id === fid) {
        holder.innerHTML = fmtBody(_data.findings[i].body || '');
        return;
      }
    }
  }

  function buildUI() {
    if (!_pane) return;
    _pane.innerHTML =
      '<div class="investigation-stage">' +
        '<header class="investigation-header">' +
          '<div class="investigation-kicker">INVESTIGATION</div>' +
          '<h2 class="investigation-title">What the record shows</h2>' +
          '<p class="investigation-intro">Documented transmissions, independent convergences, inverted symbols, ' +
            'and the questions still open — every finding this investigation has established, with its evidence. ' +
            'Select an evidence chip to open that entry in the Atlas.</p>' +
          '<div class="investigation-meta" id="investigation-meta"></div>' +
        '</header>' +
        '<div class="investigation-controls">' +
          '<input type="search" class="investigation-search" id="investigation-search" ' +
            'placeholder="Search the findings…" autocomplete="off" spellcheck="false" ' +
            'value="' + esc(_state.query) + '">' +
          '<div class="investigation-chips" id="investigation-chips">' + renderChips() + '</div>' +
        '</div>' +
        '<div class="investigation-list" id="investigation-list"></div>' +
      '</div>';

    renderList();

    var search = _pane.querySelector('#investigation-search');
    if (search) {
      search.addEventListener('input', function () {
        _state.query = search.value || '';
        _state.shown = CHUNK;
        renderList();
      });
    }

    _pane.addEventListener('click', function (ev) {
      var chip = ev.target.closest('.investigation-chip[data-cat]');
      if (chip) {
        _state.cat = chip.getAttribute('data-cat') || 'All';
        _state.shown = CHUNK;
        var chipsEl = _pane.querySelector('#investigation-chips');
        if (chipsEl) chipsEl.innerHTML = renderChips();
        renderList();
        return;
      }
      var more = ev.target.closest('#investigation-more');
      if (more) {
        _state.shown += CHUNK;
        renderList();
        return;
      }
      var src = ev.target.closest('.investigation-src[data-id]');
      if (src) {
        var id = src.getAttribute('data-id');
        if (id && typeof window.selectNode === 'function' && nodesById()[id]) {
          window.selectNode(id, true);
        }
        return;
      }
      var summary = ev.target.closest('.investigation-card-more > summary');
      if (summary) {
        // body markdown is rendered lazily on first expand
        var details = summary.parentElement;
        setTimeout(function () { if (details.open) expandBody(details); }, 0);
      }
    });
  }

  function renderError(err) {
    if (!_pane) return;
    _pane.innerHTML =
      '<div class="investigation-stage">' +
        '<header class="investigation-header">' +
          '<div class="investigation-kicker">INVESTIGATION</div>' +
          '<h2 class="investigation-title">What the record shows</h2>' +
        '</header>' +
        '<div class="investigation-empty">The findings index is not available' +
          (err && err.message ? ' (' + esc(err.message) + ')' : '') +
          '. Generate it with <code>python3 scripts/build_investigation_index.py</code> and reload.</div>' +
      '</div>';
  }

  // ── styles (integrator may move this block into app.css) ─────
  var CSS = [
    '.investigation-pane {',
    '  position: absolute;',
    '  top: 0; bottom: 0;',
    '  left: var(--eff-nav-w, 0px);',
    '  right: var(--eff-detail-w, 0px);',
    '  background:',
    '    radial-gradient(ellipse at center, rgba(212,165,90,0.04) 0%, transparent 60%),',
    '    var(--bg-0, #07090f);',
    '  overflow: auto;',
    '  transition: left var(--t-layout, 0.3s) var(--ease, ease), right var(--t-layout, 0.3s) var(--ease, ease);',
    '  color: var(--text-1, #c8c4b8);',
    '  font: 14px/1.55 -apple-system, BlinkMacSystemFont, "SF Pro Text", system-ui, sans-serif;',
    '}',
    '.investigation-stage {',
    '  max-width: 920px;',
    '  margin: 0 auto;',
    '  padding: 58px 22px 80px;          /* clears the floating app-pill */',
    '}',
    '.investigation-header { margin: 18px 0 14px; }',
    '.investigation-kicker {',
    '  font: 600 10px/1 var(--mono, "JetBrains Mono", ui-monospace, monospace);',
    '  letter-spacing: 0.28em;',
    '  color: var(--gold, #d4a55a);',
    '  opacity: 0.9;',
    '}',
    '.investigation-title {',
    '  margin: 10px 0 8px;',
    '  font: 600 24px/1.2 -apple-system, BlinkMacSystemFont, "SF Pro Display", system-ui, sans-serif;',
    '  color: var(--text-0, #ece8dc);',
    '  letter-spacing: 0.01em;',
    '}',
    '.investigation-intro {',
    '  margin: 0;',
    '  max-width: 640px;',
    '  font-size: 13px;',
    '  color: var(--text-2, #8e8a80);',
    '}',
    '.investigation-meta {',
    '  margin-top: 10px;',
    '  font: 500 10.5px/1 var(--mono, "JetBrains Mono", ui-monospace, monospace);',
    '  letter-spacing: 0.08em;',
    '  color: var(--text-3, #5c594f);',
    '}',
    '.investigation-controls {',
    '  position: sticky;',
    '  top: 0;',
    '  z-index: 3;',
    '  margin: 0 -6px;',
    '  padding: 10px 6px 10px;',
    '  background: linear-gradient(var(--bg-0, #07090f) 78%, transparent);',
    '}',
    '.investigation-search {',
    '  width: 100%;',
    '  box-sizing: border-box;',
    '  padding: 8px 12px;',
    '  border: 1px solid rgba(212,165,90,0.22);',
    '  border-radius: 8px;',
    '  background: var(--bg-1, #0c0f16);',
    '  color: var(--text-1, #c8c4b8);',
    '  font: 400 13px/1.4 -apple-system, BlinkMacSystemFont, system-ui, sans-serif;',
    '  outline: none;',
    '}',
    '.investigation-search:focus { border-color: var(--gold, #d4a55a); }',
    '.investigation-search::placeholder { color: var(--text-3, #5c594f); }',
    '.investigation-chips {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  gap: 6px;',
    '  margin-top: 9px;',
    '}',
    '.investigation-chip {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 6px;',
    '  padding: 4px 10px;',
    '  border: 1px solid rgba(var(--inv-chip, 212,165,90), 0.30);',
    '  border-radius: 999px;',
    '  background: transparent;',
    '  color: var(--text-2, #b9bec8);',
    '  font: 500 10.5px/1 var(--mono, "JetBrains Mono", ui-monospace, monospace);',
    '  letter-spacing: 0.05em;',
    '  cursor: pointer;',
    '}',
    '.investigation-chip:hover { border-color: rgba(var(--inv-chip, 212,165,90), 0.7); color: var(--text-1, #e6e6e6); }',
    '.investigation-chip.is-active {',
    '  border-color: rgb(var(--inv-chip, 212,165,90));',
    '  background: rgba(var(--inv-chip, 212,165,90), 0.10);',
    '  color: var(--text-0, #ece8dc);',
    '}',
    '.investigation-chip-n {',
    '  font-size: 9px;',
    '  opacity: 0.65;',
    '}',
    '.investigation-list {',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 10px;',
    '  margin-top: 14px;',
    '}',
    '.investigation-card {',
    '  border: 1px solid rgba(212,165,90,0.13);',
    '  border-radius: 10px;',
    '  background: rgba(255,255,255,0.015);',
    '  padding: 13px 16px 12px;',
    '  content-visibility: auto;',
    '  contain-intrinsic-size: auto 140px;',
    '}',
    '.investigation-card:hover { border-color: rgba(212,165,90,0.30); }',
    '.investigation-card-head {',
    '  display: flex;',
    '  align-items: baseline;',
    '  gap: 10px;',
    '  flex-wrap: wrap;',
    '}',
    '.investigation-badge {',
    '  flex: none;',
    '  padding: 3px 8px;',
    '  border: 1px solid;',
    '  border-radius: 4px;',
    '  font: 600 9px/1 var(--mono, "JetBrains Mono", ui-monospace, monospace);',
    '  letter-spacing: 0.12em;',
    '  text-transform: uppercase;',
    '  white-space: nowrap;',
    '}',
    '.investigation-card-title {',
    '  margin: 0;',
    '  font: 600 15px/1.35 -apple-system, BlinkMacSystemFont, "SF Pro Text", system-ui, sans-serif;',
    '  color: var(--text-0, #ece8dc);',
    '}',
    '.investigation-card-summary {',
    '  margin: 8px 0 0;',
    '  font-size: 13px;',
    '  color: var(--text-1, #c8c4b8);',
    '}',
    '.investigation-card-more { margin-top: 8px; }',
    '.investigation-card-more > summary {',
    '  display: inline-block;',
    '  cursor: pointer;',
    '  font: 500 10.5px/1 var(--mono, "JetBrains Mono", ui-monospace, monospace);',
    '  letter-spacing: 0.08em;',
    '  color: var(--gold, #d4a55a);',
    '  opacity: 0.85;',
    '  user-select: none;',
    '  -webkit-user-select: none;',
    '}',
    '.investigation-card-more > summary:hover { opacity: 1; }',
    '.investigation-card-more > summary::marker { color: var(--gold-soft, #a87f3e); }',
    '.investigation-card-body {',
    '  margin-top: 8px;',
    '  padding: 10px 12px;',
    '  border-left: 2px solid rgba(212,165,90,0.25);',
    '  background: rgba(0,0,0,0.18);',
    '  border-radius: 0 8px 8px 0;',
    '  font-size: 13px;',
    '  color: var(--text-1, #c8c4b8);',
    '}',
    '.investigation-card-body p { margin: 0 0 9px; }',
    '.investigation-card-body p:last-child { margin-bottom: 0; }',
    '.investigation-card-body ul { margin: 0 0 9px; padding-left: 18px; }',
    '.investigation-card-body li { margin: 0 0 6px; }',
    '.investigation-card-body code {',
    '  font-family: var(--mono, "JetBrains Mono", ui-monospace, monospace);',
    '  font-size: 11.5px;',
    '  color: var(--gold, #d4a55a);',
    '}',
    '.investigation-bodyhead {',
    '  margin: 4px 0 8px;',
    '  font: 600 12px/1.3 -apple-system, BlinkMacSystemFont, system-ui, sans-serif;',
    '  color: var(--text-0, #ece8dc);',
    '}',
    '.investigation-tablewrap { overflow-x: auto; margin: 0 0 9px; }',
    '.investigation-tablewrap table {',
    '  border-collapse: collapse;',
    '  font-size: 11.5px;',
    '}',
    '.investigation-tablewrap th, .investigation-tablewrap td {',
    '  border: 1px solid rgba(212,165,90,0.16);',
    '  padding: 4px 8px;',
    '  text-align: left;',
    '  vertical-align: top;',
    '}',
    '.investigation-tablewrap th {',
    '  color: var(--gold, #d4a55a);',
    '  font-weight: 600;',
    '  background: rgba(212,165,90,0.05);',
    '}',
    '.investigation-srcs {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 5px;',
    '  margin-top: 10px;',
    '}',
    '.investigation-srcs-label {',
    '  font: 500 9px/1 var(--mono, "JetBrains Mono", ui-monospace, monospace);',
    '  letter-spacing: 0.14em;',
    '  text-transform: uppercase;',
    '  color: var(--text-3, #5c594f);',
    '  margin-right: 3px;',
    '}',
    '.investigation-src {',
    '  padding: 3px 9px;',
    '  border: 1px solid rgba(212,165,90,0.25);',
    '  border-radius: 999px;',
    '  background: transparent;',
    '  color: var(--text-2, #b9bec8);',
    '  font: 500 10px/1.3 var(--mono, "JetBrains Mono", ui-monospace, monospace);',
    '  cursor: pointer;',
    '}',
    '.investigation-src:hover {',
    '  border-color: var(--gold, #d4a55a);',
    '  color: var(--gold, #d4a55a);',
    '}',
    '.investigation-src--miss {',
    '  border-style: dashed;',
    '  border-color: rgba(255,255,255,0.10);',
    '  color: var(--text-3, #5c594f);',
    '  cursor: default;',
    '}',
    '.investigation-more-btn {',
    '  margin: 8px auto 0;',
    '  padding: 8px 22px;',
    '  border: 1px solid rgba(212,165,90,0.30);',
    '  border-radius: 999px;',
    '  background: transparent;',
    '  color: var(--gold, #d4a55a);',
    '  font: 500 11px/1 var(--mono, "JetBrains Mono", ui-monospace, monospace);',
    '  letter-spacing: 0.08em;',
    '  cursor: pointer;',
    '}',
    '.investigation-more-btn:hover { background: rgba(212,165,90,0.08); }',
    '.investigation-loading, .investigation-empty {',
    '  margin-top: 28px;',
    '  font: 500 11px/1.6 var(--mono, "JetBrains Mono", ui-monospace, monospace);',
    '  letter-spacing: 0.06em;',
    '  color: var(--text-3, #5c594f);',
    '}',
    '.investigation-empty code { color: var(--gold, #d4a55a); font-family: inherit; }',
  ].join('\n');

  function injectStyle() {
    if (document.getElementById('investigation-style')) return;
    var style = document.createElement('style');
    style.id = 'investigation-style';
    style.textContent = CSS;
    document.head.appendChild(style);
  }

  // ── boundary contract ─────────────────────────────────────────
  function render(pane) {
    if (!pane) return;
    _pane = pane;
    injectStyle();
    pane.classList.add('investigation-pane');
    pane.innerHTML =
      '<div class="investigation-stage">' +
        '<header class="investigation-header">' +
          '<div class="investigation-kicker">INVESTIGATION</div>' +
          '<h2 class="investigation-title">What the record shows</h2>' +
        '</header>' +
        '<div class="investigation-loading">opening the case file…</div>' +
      '</div>';
    var token = ++_loadToken;
    load()
      .then(function () {
        if (_pane !== pane || token !== _loadToken) return;
        buildUI();
      })
      .catch(function (err) {
        if (_pane !== pane || token !== _loadToken) return;
        renderError(err);
      });
  }

  function unmount() {
    _pane = null;
    _loadToken++;
    _nodesById = null;   // vault data may be rebuilt between mounts
  }

  window._investigationView = { render: render, unmount: unmount };
})();
