// CODEX ATLAS — Alphabet Glyph Data
// 22 Proto-Sinaitic letters: hieroglyphic source → modern descendants
// Each entry now carries investigationHighlight (the key vault finding for this letter)
// and relatedNodes (vault node IDs to open from the expanded card).

window.ALPHA_GLYPH_DATA = [
  {
    letter: 'A', name: 'Aleph', meaning: 'ox', gardiner: 'E1',
    unicode: 0x130D2, phoneme: 'ʾ (glottal stop)', greek: 'Α alpha', latin: 'A',
    hebrew: 'א', arabic: 'ا', phoenician: '\u{10900}',
    note: 'You are reading a rotated ox-skull. The letter A is an upside-down ox-head — tip it forward and you see the snout and two horns. "Aleph" means ox. The very first letter of every Western alphabet is a cow.',
    investigationHighlight: 'Aleph is the first letter of every Western alphabet — but it makes no sound. A glottal stop: silence before speech. In Sefer Yetzirah, Aleph = Air, the first of 3 Mother Letters (Air / Water / Fire). In Islamic mysticism, the Alif supports all vowels but has no independent voice. In Hebrew mysticism, God\'s first act of creation was through Aleph — the inaudible beginning. Every alphabet in the Western tradition starts with silence.',
    relatedNodes: ['alphabet-sefer-yetzirah', 'alphabet-ilm-al-huruf', 'alphabet-hebrew-aleph-bet', 'alphabet-creation-by-word'],
  },
  {
    letter: 'B', name: 'Beth', meaning: 'house', gardiner: 'O1',
    unicode: 0x13250, phoneme: 'b', greek: 'Β beta', latin: 'B',
    hebrew: 'ב', arabic: 'ب', phoenician: '\u{10901}',
    note: 'This letter is a floor plan. The hieroglyph is a bird\'s-eye view of an Egyptian house — the rectangle is the courtyard, the notch is the doorway. Genesis begins with Beth: בְּרֵאשִׁית (Bereishit). The Bible\'s first letter is an architectural diagram.',
    investigationHighlight: 'Genesis opens with Beth — the second letter of the alphabet, not the first. In Sefer Yetzirah this is deliberate: God began creation not with the first letter but with the letter that means "house." The universe was built as a house. The Phoenician letter-form IS a floor plan (courtyard + doorway notch). Devanagari = "city of the gods." Arabic geometric calligraphy treats every mosque wall as scripture. Three traditions independently concluded: the letter is an architectural blueprint, and creation is a building.',
    relatedNodes: ['alphabet-sefer-yetzirah', 'alphabet-hebrew-aleph-bet', 'alphabet-creation-by-word', 'alphabet-letter-as-cosmos', 'alphabet-arabic-calligraphy'],
  },
  {
    letter: 'G', name: 'Gimel', meaning: 'camel / throw-stick', gardiner: 'T14',
    unicode: 0x13319, phoneme: 'g', greek: 'Γ gamma', latin: 'C / G',
    hebrew: 'ג', arabic: 'ج', phoenician: '\u{10902}',
    note: 'The hump of a camel. The L-shape of Gamma (Γ) traces the neck and single hump. In Egyptian the throw-stick hieroglyph was used for the "g" sound — a common scribal pun (the word for throw-stick sounded like a Semitic word for camel-hump).',
    investigationHighlight: 'One Phoenician Gimel became two Latin letters: C and G. Early Latin used C for both sounds; Romans added the diagonal leg to create G specifically to distinguish them. Gematria value: 3. The letter-number systems (Hebrew Gematria, Greek Isopsephy, Arabic Abjad) all share the same Phoenician number-scaffold: Gimel = 3, across all three traditions, because they all inherited the same letter-order from Phoenician c. 1050 BCE.',
    relatedNodes: ['alphabet-gematria-hebrew', 'alphabet-isopsephy-greek', 'alphabet-ilm-al-huruf', 'alphabet-sefer-yetzirah'],
  },
  {
    letter: 'D', name: 'Daleth', meaning: 'door', gardiner: 'O31',
    unicode: 0x1327F, phoneme: 'd', greek: 'Δ delta', latin: 'D',
    hebrew: 'ד', arabic: 'د', phoenician: '\u{10903}',
    note: 'A door or tent-flap. The triangular Delta (Δ) is the peaked shape of a leather door-hanging seen from the front. D in Latin rotated the triangle onto a vertical post: the upright post of the doorframe + the leather flap arching out = D.',
    investigationHighlight: 'Delta (Δ) names every river mouth in the world — because the Nile delta is triangular, because the triangle looks like the Greek letter Δ, because Δ looks like a door, because Daleth means "door." The word "delta" in modern geography is a 3,800-year transmission chain: Egyptian tent-flap hieroglyph → Phoenician letter → Greek alphabet → Latin geography. Every river delta on earth carries this name.',
    relatedNodes: ['alphabet-phoenician', 'alphabet-medu-netjer', 'proto-sinaitic'],
  },
  {
    letter: 'E', name: 'He', meaning: 'window / arms raised in jubilation', gardiner: 'A28',
    unicode: 0x13020, phoneme: 'h', greek: 'Ε epsilon', latin: 'E',
    hebrew: 'ה', arabic: 'ه', phoenician: '\u{10904}',
    note: 'A figure with arms raised — the Egyptian hieroglyph for jubilation or "hail!" Greeks had no H-sound equivalent so they repurposed this as the vowel E (epsilon = "bare E"). The three prongs of E still echo the raised arms and head.',
    investigationHighlight: 'He is the first of the five Greek vowels repurposed from Semitic consonants. Greeks had no H-sound — so they took this letter and reassigned it as E. This was the cognitive threshold: by adding vowels, the Greek alphabet became the first writing system capable of representing any human utterance exactly. The consequence was not just linguistic — stable written abstract nouns made Greek philosophy structurally possible. He → Epsilon → Plato.',
    relatedNodes: ['alphabet-greek-vowel-revolution', 'alphabet-phoenician', 'alphabet-hebrew-aleph-bet', 'huruf-muqattaat'],
  },
  {
    letter: 'F', name: 'Waw', meaning: 'hook / peg / mace', gardiner: 'T3',
    unicode: 0x13309, phoneme: 'w', greek: 'Υ upsilon / Ϝ digamma', latin: 'F / U / V / W / Y',
    hebrew: 'ו', arabic: 'و', phoenician: '\u{10905}',
    note: 'One letter spawned six modern letters: F, U, V, W, Y, and the Greek upsilon (Υ). The hook-peg hieroglyph made the "w" sound. Greeks used it first as the digamma Ϝ (F-sound), then as upsilon (U-sound). Latin split it further into U, V, W, and eventually Y. The most productive letter in history.',
    investigationHighlight: 'The most productive letter in history. One Phoenician hook-peg generated six modern letters: F, U, V, W, Y, and Greek Υ. "W" is literally "double U" — its name records the historical moment when scribes wrote UU to represent a sound Latin had no letter for. Every time you type U, V, W, Y, or F, you are typing a variant of a 3,800-year-old Phoenician hook. Waw also demonstrates the Greek vowel invention: it was repurposed as Upsilon, the vowel U.',
    relatedNodes: ['alphabet-greek-vowel-revolution', 'alphabet-phoenician', 'alphabet-latin'],
  },
  {
    letter: 'Z', name: 'Zayin', meaning: 'weapon (sword or axe)', gardiner: 'T7',
    unicode: 0x1330E, phoneme: 'z', greek: 'Ζ zeta', latin: 'Z',
    hebrew: 'ז', arabic: 'ز', phoenician: '\u{10906}',
    note: 'A sword or double-headed axe. Zeta (Ζ) retains the blade shape. Latin borrowed it late (from Greek) specifically to transliterate Greek words — Z appears almost nowhere in native Latin vocabulary.',
    investigationHighlight: 'Z enters Latin at the very end of the alphabet, after Y, because Julius Caesar added both Y and Z to the Roman alphabet specifically to transliterate Greek loanwords. Z barely exists in native Latin; its position at the end records the moment of borrowing. Gematria value: 7 — the number of Shabbat, the week, completion. The weapon-letter lands on the number of rest.',
    relatedNodes: ['alphabet-gematria-hebrew', 'alphabet-isopsephy-greek', 'alphabet-latin'],
  },
  {
    letter: 'H', name: 'Heth', meaning: 'fence / courtyard wall', gardiner: 'O4',
    unicode: 0x13254, phoneme: 'ḥ (emphatic h)', greek: 'Η eta', latin: 'H',
    hebrew: 'ח', arabic: 'ح', phoenician: '\u{10907}',
    note: 'A fence or courtyard enclosure seen from above — the double horizontal bars are the fence posts. Greeks had no emphatic-H consonant so they turned it into the long-E vowel eta (Η). Latin kept the consonant as H but thinned the fence to two uprights and a crossbar.',
    investigationHighlight: 'The Masoretes (c. 500–1000 CE) invented their entire vowel-pointing system partly to preserve distinctions like He/Heth — two aspirated h-sounds that merged in later Hebrew pronunciation. After Hebrew ceased to be a vernacular, nobody could read Torah correctly without the pointing system. The Masoretes also accidentally created "Jehovah": the divine name YHWH was written with the vowels of Adonai as a reading-prohibition signal, and 16th-century Christian scholars misread it as a pronounceable hybrid.',
    relatedNodes: ['alphabet-masoretes', 'alphabet-hebrew-aleph-bet', 'alphabet-aramaic'],
  },
  {
    letter: '', name: 'Teth', meaning: 'basket / coiled rope', gardiner: 'V28',
    unicode: 0x1339B, phoneme: 'ṭ (emphatic t)', greek: 'Θ theta', latin: '(none — dropped)',
    hebrew: 'ט', arabic: 'ط', phoenician: '\u{10908}',
    note: 'A wickerwork basket or coiled rope seen from above — the circle with an interior mark. Greek theta (Θ) kept the shape almost exactly. Latin had no emphatic consonant for this, so Teth was dropped entirely — the first letter lost in the Latin transition.',
    investigationHighlight: 'The first casualty. Every script adaptation involves losses: letters for sounds the receiving language cannot make get dropped. Teth is the clearest case — an emphatic dental that Greek kept as Θ (theta) but Latin simply deleted. Wherever the Latin alphabet passes through a Semitic sound it has no equivalent for, that sound disappears. The knowledge-destroyed-by-conquest pattern applies to phonemes as well as scripts.',
    relatedNodes: ['alphabet-greek-vowel-revolution', 'alphabet-phoenician', 'alphabet-latin'],
  },
  {
    letter: 'I', name: 'Yod', meaning: 'hand / arm', gardiner: 'D36',
    unicode: 0x1309D, phoneme: 'y', greek: 'Ι iota', latin: 'I / J',
    hebrew: 'י', arabic: 'ي', phoenician: '\u{10909}',
    note: 'The hand and forearm. Yod is the smallest letter in the Hebrew alphabet — a single bent stroke. Jesus references this in Matthew 5:18: "not one jot (yod) or tittle will pass from the Law." The word "jot" in English is literally the Hebrew letter-name Yod, via Greek iota.',
    investigationHighlight: 'The smallest letter carries the most mystical weight. In Sefer Yetzirah, Yod is the subtlest element. In Islamic mysticism, the dot under Yaa (ي) is the primordial point from which all creation flows — the entire universe compressed to a single geometric point before expanding. Jesus says "not one Yod shall pass from the law" (Matthew 5:18) — the English word "jot" IS the letter-name, via Greek iota. The Aramaic transmission: Jesus spoke this in Aramaic; it was recorded in Greek; it entered English via the Hebrew letter-name.',
    relatedNodes: ['alphabet-sefer-yetzirah', 'alphabet-ilm-al-huruf', 'alphabet-greek-vowel-revolution', 'alphabet-hebrew-aleph-bet', 'alphabet-aramaic'],
  },
  {
    letter: 'K', name: 'Kaph', meaning: 'open palm of hand', gardiner: 'D46',
    unicode: 0x130A7, phoneme: 'k', greek: 'Κ kappa', latin: 'K',
    hebrew: 'כ', arabic: 'ك', phoenician: '\u{1090A}',
    note: 'The open palm of the hand, seen from the front — the vertical stroke is the arm, the angled strokes are the fingers. Kappa (Κ) and K both reproduce this shape. Used rarely in Latin (which preferred C for the k-sound) but preserved in words borrowed from Greek.',
    investigationHighlight: 'Hebrew Kaph has two forms: כ (open, mid-word) and ך (closed, final position) — one of 5 Hebrew "sofit" (final-form) letters. The distinction between open and closed, mid-word and final, is a scribal tradition over 2,500 years old preserved exactly by the Masoretes. The open palm / closed fist duality encodes a philosophical reading: the same letter is open when giving, closed when finishing.',
    relatedNodes: ['alphabet-masoretes', 'alphabet-hebrew-aleph-bet', 'alphabet-sefer-yetzirah'],
  },
  {
    letter: 'L', name: 'Lamedh', meaning: 'oxgoad / shepherd\'s crook', gardiner: 'S38',
    unicode: 0x132FE, phoneme: 'l', greek: 'Λ lambda', latin: 'L',
    hebrew: 'ל', arabic: 'ل', phoenician: '\u{1090B}',
    note: 'The shepherd\'s crook used to goad cattle — the hooked staff. Lambda (Λ) is the inverted crook-hook. The tall reaching shape of ל in Hebrew (the only letter that reaches above the headline) still suggests the upward hook of the goad.',
    investigationHighlight: 'Lamedh is the only Hebrew letter that rises above the top baseline — ל reaches upward where all other letters occupy the middle or lower zones. In kabbalistic tradition this vertical distinction is cosmological: the letter that teaches (Lamed comes from the root "to learn/teach") must reach higher than the others. Lamedh begins the word לֵב (lev, heart). The tallest letter, in a tradition where letter-height is not aesthetic but cosmic.',
    relatedNodes: ['alphabet-sefer-yetzirah', 'alphabet-hebrew-aleph-bet', 'alphabet-letter-as-cosmos'],
  },
  {
    letter: 'M', name: 'Mem', meaning: 'water', gardiner: 'N35',
    unicode: 0x13216, phoneme: 'm', greek: 'Μ mu', latin: 'M',
    hebrew: 'מ', arabic: 'م', phoenician: '\u{1090C}',
    note: 'This wavy line has meant water for 3,800 years. Mem = water. The W-wave pattern of M directly descends from the Egyptian water hieroglyph — a horizontal wavy line. In virtually every script that descends from Phoenician, M sounds like "m" and looks like waves. The most visually obvious pictogram survival in the modern alphabet.',
    investigationHighlight: 'Mem is one of Sefer Yetzirah\'s 3 Mother Letters — Aleph/Mem/Shin = Air/Water/Fire. The primordial triad from which the universe was constructed. Water comes first in Genesis 1:2 — before light, before land, before life. The word for mother in Hebrew is אֵם (em) — Aleph-Mem, Air-Water. Every creation cosmology that uses water as the primordial element (Babylonian Tiamat, Greek chaos-sea, Hindu primordial ocean) is echoing the cosmic status encoded in this letter.',
    relatedNodes: ['alphabet-sefer-yetzirah', 'alphabet-creation-by-word', 'alphabet-hebrew-aleph-bet', 'alphabet-medu-netjer'],
  },
  {
    letter: 'N', name: 'Nun', meaning: 'snake / fish', gardiner: 'I10',
    unicode: 0x13193, phoneme: 'n', greek: 'Ν nu', latin: 'N',
    hebrew: 'נ', arabic: 'ن', phoenician: '\u{1090D}',
    note: 'A snake (Egyptian cobra) in profile — the S-curve body. The undulating N letterform descends from a snake\'s silhouette. In some traditions Nun means "fish" — the serpentine profile works for both.',
    investigationHighlight: 'Nun has two Hebrew forms: נ (mid-word) and ן (final, a long descending stroke). In the Talmud, Nun is the letter of נְפֶשׁ (nefesh, soul) — the snake/fish in the water is the soul moving through the body. The serpent-letter is the soul-letter. In gematria, Nun = 50 — the number of the Jubilee, the fiftieth year of liberation. The soul-snake-fish letter lands on the liberation number.',
    relatedNodes: ['alphabet-sefer-yetzirah', 'alphabet-gematria-hebrew', 'alphabet-hebrew-aleph-bet'],
  },
  {
    letter: 'S', name: 'Samekh', meaning: 'fish / pillar / spine', gardiner: 'K1',
    unicode: 0x1319B, phoneme: 's', greek: 'Ξ xi (archaic) / unclear', latin: 'S (via sigma)',
    hebrew: 'ס', arabic: 'س', phoenician: '\u{1090E}',
    note: 'A fish, tent-peg, or supporting pillar — scholars disagree. Samekh fed into S in Hebrew but its Greek path is debated; sigma (Σ) may derive from a different letter. The letter\'s shape — a closed circle or fish-bone — supports the fish reading.',
    investigationHighlight: 'The most disputed origin of the 22. Samekh\'s hieroglyphic source is genuinely contested — fish, tent-peg, or pillar — and its path into Greek is unclear. This is one of the few cases where the Proto-Sinaitic acrophonic principle (letter = picture of the thing whose name begins with that sound) breaks down. Samekh shows the limit of how far back we can trace the chain with certainty.',
    relatedNodes: ['alphabet-phoenician', 'proto-sinaitic', 'alphabet-medu-netjer'],
  },
  {
    letter: 'O', name: 'Ayin', meaning: 'eye', gardiner: 'D4',
    unicode: 0x13079, phoneme: 'ʿ (pharyngeal consonant)', greek: 'Ο omicron', latin: 'O',
    hebrew: 'ע', arabic: 'ع', phoenician: '\u{1090F}',
    note: 'This was an eye. Ayin (עַיִן) literally means "eye" in Hebrew, and the hieroglyph is an eye in outline. Greeks had no pharyngeal consonant for "ʿ" — the sound doesn\'t exist in Greek — so they repurposed the eye-sign as the vowel O. This is why O is shaped like an eye: because it IS an eye, 3,000 years old.',
    investigationHighlight: 'O is an eye. The pharyngeal consonant ʿ (the sound in the name ʿAli) does not exist in Greek or Latin. So Greeks took the eye-shaped letter and made it the circle vowel O (omicron = "small O"). The Arabic letter ع still visually echoes an eye with a descending tail. The Aramaic dialect of Jesus preserves this sound in ʿAramaya (Aramaic itself). Every O you read is a 3,800-year-old Semitic eye that Greek philosophy repurposed as a vowel.',
    relatedNodes: ['alphabet-greek-vowel-revolution', 'alphabet-ilm-al-huruf', 'alphabet-aramaic'],
  },
  {
    letter: 'P', name: 'Pe', meaning: 'mouth', gardiner: 'D21',
    unicode: 0x1308B, phoneme: 'p', greek: 'Π pi', latin: 'P',
    hebrew: 'פ', arabic: 'ف', phoenician: '\u{10910}',
    note: 'The mouth. Pe (פֶּה) means "mouth" in Hebrew. Pi (Π) and P both trace to the lips and jaw of an open mouth seen in profile. The "p" sound is a labial — made with the lips. The lips that make the sound are also the picture that became the letter.',
    investigationHighlight: 'In Sefer Yetzirah, Pe is one of the 7 "double letters" — letters that carry two sounds depending on whether they carry a dot (פ = P / ף = F). The mouth as creation-instrument is central: in Jewish mysticism, God speaks the world into existence; the mouth-letter is a creation-tool. The Logos / Memra / Vāc convergence: Hebrew, Aramaic, Greek, Sanskrit — four traditions locating the creative power in speech, in the mouth, in this letter.',
    relatedNodes: ['alphabet-sefer-yetzirah', 'alphabet-creation-by-word', 'alphabet-hebrew-aleph-bet', 'alphabet-aramaic'],
  },
  {
    letter: '', name: 'Tsade', meaning: 'plant / fish-hook / man on side', gardiner: 'M17',
    unicode: 0x131CB, phoneme: 'ṣ (emphatic s)', greek: 'Ϻ san (archaic) / Ϡ sampi', latin: '(none)',
    hebrew: 'צ', arabic: 'ص', phoenician: '\u{10911}',
    note: 'A papyrus plant, fish-hook, or a man lying on his side — the most disputed origin. Became Coptic Ϣ. Dropped from Latin. Survives in Hebrew as Tsade (צ) and in Arabic abjad numerals. A letter that fell through the cracks of the European tradition.',
    investigationHighlight: 'Tsade is what the European tradition dropped and the Semitic tradition kept. The emphatic sibilant ṣ has no equivalent in Greek or Latin — it appears in Arabic, Hebrew, and Aramaic but disappeared from every European language. It is also the letter of the Righteous: Tzaddik (צַדִּיק) means righteous person. In Sefer Yetzirah, Tsade governs the month and virtue of righteousness. The letter the West lost is the one that names the just.',
    relatedNodes: ['alphabet-hebrew-aleph-bet', 'alphabet-arabic-calligraphy', 'alphabet-sefer-yetzirah'],
  },
  {
    letter: 'Q', name: 'Qoph', meaning: 'needle eye / thread / monkey', gardiner: 'Aa28',
    unicode: 0x1342A, phoneme: 'q (back-of-throat k)', greek: 'Ϙ qoppa (archaic)', latin: 'Q',
    hebrew: 'ק', arabic: 'ق', phoenician: '\u{10912}',
    note: 'A needle with thread, or possibly a monkey\'s head. Greek qoppa (Ϙ) survived briefly as an archaic letter for the qu-cluster, then was dropped from the standard Greek alphabet but kept in numeric use (= 90). Latin kept Q exclusively for the "qu" combination. In modern English, Q almost never appears without U — a 3,000-year phonological rule persisting as spelling convention.',
    investigationHighlight: 'The Q-U rule in English spelling is a fossilized Semitic phonological habit. The uvular q-sound in Semitic languages was always followed by a vowel; this became a Latin scribal convention (Q only before U) which became an English spelling rule your teachers enforced. Every English spelling lesson about QU is transmitting a convention from Phoenician phonology, 3,000 years later, without anyone involved knowing it.',
    relatedNodes: ['alphabet-hebrew-aleph-bet', 'alphabet-phoenician', 'alphabet-gematria-hebrew'],
  },
  {
    letter: 'R', name: 'Resh', meaning: 'head', gardiner: 'D1',
    unicode: 0x13076, phoneme: 'r', greek: 'Ρ rho', latin: 'R',
    hebrew: 'ר', arabic: 'ر', phoenician: '\u{10913}',
    note: 'A human head in profile. Resh (רֹאשׁ) means "head" in Hebrew. The circle-with-a-descender shape of Rho (Ρ) and R is the skull seen from the side. P and R were once identical in early alphabets — the diagonal leg was added to R to distinguish them, a leg the human profile head did not have.',
    investigationHighlight: 'Resh begins the Hebrew word רוּחַ (ruach — spirit, wind, breath) which appears in Genesis 1:2: "the spirit/wind of God moved over the waters." Ruach is also the word for the human spirit. In kabbalistic astrology, Resh corresponds to the sun. The head-letter governs spirit and the sun — the same correspondence that appears in Egyptian Ra (the solar head), in Pythagorean music theory (sun = center), and in Vedic cosmology.',
    relatedNodes: ['alphabet-gematria-hebrew', 'alphabet-sefer-yetzirah', 'alphabet-hebrew-aleph-bet', 'alphabet-medu-netjer'],
  },
  {
    letter: 'S', name: 'Shin', meaning: 'tooth', gardiner: 'F18',
    unicode: 0x13111, phoneme: 'š (sh-sound)', greek: 'Σ sigma', latin: 'S',
    hebrew: 'ש', arabic: 'ش', phoenician: '\u{10914}',
    note: 'Three teeth. Shin (שִׁן) means "tooth" in Hebrew. The three-pronged W-shape of ש is three teeth in a jaw. Sigma (Σ) flattened the three prongs to a zigzag. The English letter S still traces those three dental ridges — you are looking at a row of teeth every time you read the letter S.',
    investigationHighlight: 'The Priestly Blessing (Birkat Kohanim) forms the letter Shin with the fingers — splitting them into two groups of two around the thumb. Leonard Nimoy, a Jewish actor who saw this blessing as a child in synagogue, gave this hand gesture to Mr. Spock as the Vulcan salute. Shin = fire, the third of Sefer Yetzirah\'s 3 Mother Letters (Air/Water/Fire). Every time someone flashes "live long and prosper," they are making a 3,000-year-old Hebrew fire-letter from a Priestly Blessing.',
    relatedNodes: ['alphabet-hebrew-aleph-bet', 'alphabet-sefer-yetzirah', 'alphabet-ilm-al-huruf'],
  },
  {
    letter: 'T', name: 'Taw', meaning: 'mark / cross / sign', gardiner: 'Z9',
    unicode: 0x133F4, phoneme: 't', greek: 'Τ tau', latin: 'T',
    hebrew: 'ת', arabic: 'ت', phoenician: '\u{10915}',
    note: 'The last letter was a cross or X mark. In ancient Phoenician and early Hebrew script, Taw was written as an X or a + cross. Ezekiel 9:4 — God tells the angel to place a Taw on the foreheads of the righteous before the judgment of Jerusalem. The original mark of salvation was a cross-shaped letter. Tau was the last letter, the mark, the end.',
    investigationHighlight: 'The original Taw was a cross. In Paleo-Hebrew and early Phoenician, Taw was written as X or +. Ezekiel 9:4 — God commands the angel to mark the foreheads of the righteous with a Taw before judgment. Tertullian (c. 200 CE) pointed this out: the saving mark in Ezekiel is the tau/cross. The connection between Taw and the cross predates Christianity by at least 1,000 years — it was built into the letter\'s shape. The last letter of the Hebrew alphabet was already a cross before the crucifixion.',
    relatedNodes: ['alphabet-hebrew-aleph-bet', 'alphabet-sefer-yetzirah', 'alphabet-aramaic', 'alphabet-letter-as-cosmos'],
  },

  // ── Latin-only additions (scriptOnly: ['latin']) ─────────────────────────
  // Letters that exist in the Latin/modern alphabet but have no Phoenician root entry above.
  // Only shown when _script === 'latin'.
  {
    letter: 'C', name: 'C (from Gimel)', meaning: 'same root as G', gardiner: 'T14',
    unicode: 0x13319, phoneme: 'k / s', greek: 'Γ gamma', latin: 'C',
    hebrew: 'ג', arabic: 'ج', phoenician: '\u{10902}', scriptOnly: ['latin'],
    note: 'C and G are the same Phoenician letter. Early Latin used C for both k and g sounds — "Caesar" was pronounced "Kaiser." Romans added the leg to create G when they needed to distinguish them, keeping C for the k-sound.',
    investigationHighlight: 'C is G\'s twin. One Phoenician Gimel became two Latin letters: C (for the k-sound) and G (retrofitted by adding a leg). The soft C (as in "city") came later in Romance languages. Every time English spelling uses C and G inconsistently — "cat" vs "city," "get" vs "gem" — it is displaying the scar left by this 2,300-year-old split.',
    relatedNodes: ['alphabet-phoenician', 'alphabet-latin', 'alphabet-greek-vowel-revolution'],
  },
  {
    letter: 'J', name: 'J (from Yod)', meaning: 'consonantal I — medieval addition', gardiner: 'D36',
    unicode: 0x1309D, phoneme: 'dʒ / j / y', greek: 'Ι iota', latin: 'J',
    hebrew: 'י', arabic: 'ي', phoenician: '\u{10909}', scriptOnly: ['latin'],
    note: 'J is a variant I. In medieval manuscripts, scribes began drawing I with a tail (J) at the start of words to distinguish the consonantal Y-sound from the vowel I. J became a separate letter around the 17th century — making it one of the youngest letters in the alphabet.',
    investigationHighlight: 'J is only ~400 years old as a distinct letter. It is a variant form of I (Yod), used when I was consonantal (y-sound in Latin, dʒ-sound in English after Norman influence). "Jehovah" itself is a late invention: the J in "Jehovah" did not exist when the Masoretes wrote the vowel-prohibition code that 16th-century scholars misread. The most common divine name in English begins with a letter invented in the 1600s.',
    relatedNodes: ['alphabet-masoretes', 'alphabet-hebrew-aleph-bet', 'alphabet-latin'],
  },
  {
    letter: 'U', name: 'U (from Waw/V)', meaning: 'vowel split from V — medieval', gardiner: 'T3',
    unicode: 0x13309, phoneme: 'uː', greek: 'Υ upsilon', latin: 'U',
    hebrew: 'ו', arabic: 'و', phoenician: '\u{10905}', scriptOnly: ['latin'],
    note: 'U and V were the same letter in classical Latin. V was used at the start of words; U in the middle. The distinction was formalized in the Middle Ages — making both U and V (and W and Y) descendants of the single Phoenician Waw hook-peg.',
    investigationHighlight: 'U V W Y F — five modern letters from one Phoenician hook. Waw (ו) is the most productive letter in history. U and V separated gradually in medieval manuscripts. W was invented by Anglo-Saxon scribes writing UU or VV for a sound Latin had no letter for — its name "double-U" is literally a description of its creation. Every time you write U, V, W, or Y you are writing variants of the same 3,800-year-old Phoenician peg.',
    relatedNodes: ['alphabet-latin', 'alphabet-greek-vowel-revolution', 'alphabet-phoenician'],
  },
  {
    letter: 'V', name: 'V (from Waw)', meaning: 'consonantal form of U', gardiner: 'T3',
    unicode: 0x13309, phoneme: 'v / w', greek: 'Υ upsilon / Ϝ digamma', latin: 'V',
    hebrew: 'ו', arabic: 'و', phoenician: '\u{10905}', scriptOnly: ['latin'],
    note: 'In classical Latin, V was the only form — it represented both the vowel U and the consonant W/V sounds. The distinction between U and V is medieval. The name "Julius" in Latin was pronounced "Yulius" — the consonant V/I was a Y-sound, not a V-sound.',
    investigationHighlight: '"Julius Caesar" = "Yulius Kaesar." Classical Latin had no V-sound (as in English "vine") — what is now written V was pronounced as W. The V-sound entered Latin through late loanwords from Greek and Etruscan. The angular V shape descends directly from the Phoenician Waw hook, which became Upsilon (Υ) in Greek and then rotated into the V form in Etruscan and Latin.',
    relatedNodes: ['alphabet-latin', 'alphabet-phoenician', 'alphabet-greek-vowel-revolution'],
  },
  {
    letter: 'W', name: 'W (double-U)', meaning: 'Anglo-Saxon invention — no ancient root', gardiner: 'T3',
    unicode: 0x13309, phoneme: 'w', greek: '(none)', latin: 'W',
    hebrew: 'ו', arabic: 'و', phoenician: '\u{10905}', scriptOnly: ['latin'],
    note: '"W" is literally "double U." Anglo-Saxon scribes in the 7th–8th century began writing UU or VV to represent a sound (the English W) that Latin had no letter for. By the 11th century it was treated as a single letter. Its name in English still records the moment of invention.',
    investigationHighlight: 'W is the only letter in the English alphabet whose name is a description of how it was built: "double U." It was invented by Germanic scribes, not inherited from Rome or Greece or Phoenicia. Yet its ancestry is Phoenician Waw — all five letters F U V W Y trace to the same hook-peg hieroglyph. The most modern-looking letter has the oldest possible ancestor.',
    relatedNodes: ['alphabet-latin', 'alphabet-elder-futhark'],
  },
  {
    letter: 'X', name: 'X (from Greek Chi)', meaning: 'ks sound — Greek import', gardiner: 'Aa28',
    unicode: 0x1342A, phoneme: 'ks', greek: 'Χ chi / Ξ xi', latin: 'X',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['latin'],
    note: 'Latin X represents the "ks" cluster. It may derive from the Greek letter Chi (Χ) or possibly Samekh (ס) via an Etruscan route. Julius Caesar added both X (already present) and the letters Y and Z to formalize Greek loanword transliteration.',
    investigationHighlight: 'X marks a transmission puzzle. Its "ks" sound could come from Greek Chi (Χ, the kh-sound) or from Samekh (ס, the fish/pillar letter) via Etruscan. Different scholars argue different routes. X is also the letter the ancient Taw (cross-mark) resembled — raising the possibility that the Christian use of X for Christ (Chi-Rho monogram, XP) preserved an ancient cross-letter tradition older than the crucifixion.',
    relatedNodes: ['alphabet-greek-vowel-revolution', 'alphabet-phoenician', 'alphabet-latin'],
  },
  {
    letter: 'Y', name: 'Y (from Upsilon)', meaning: 'Greek loanword letter — Julius Caesar addition', gardiner: 'T3',
    unicode: 0x13309, phoneme: 'y / iː', greek: 'Υ upsilon', latin: 'Y',
    hebrew: 'ו', arabic: 'و', phoenician: '\u{10905}', scriptOnly: ['latin'],
    note: 'Julius Caesar added Y (along with Z) to the Latin alphabet specifically to transliterate Greek words. Y represents the Greek Upsilon (Υ) sound. Like Z, Y sits at the end of the alphabet because it was added late.',
    investigationHighlight: 'Y is a direct Greek import. Julius Caesar ordered Y and Z added to the end of the Latin alphabet (after X) to handle Greek loanwords — which is why the English alphabet ends X Y Z, with the last two letters in the positions of late arrivals. Y traces back through Upsilon to Waw — the same Phoenician hook that gave Latin F, U, V, and W. One ancient letter, six modern shapes.',
    relatedNodes: ['alphabet-greek-vowel-revolution', 'alphabet-latin', 'alphabet-phoenician'],
  },

  // ── Greek-only additions (scriptOnly: ['greek']) ──────────────────────────
  // Φ Χ Ψ Ω — four letters Greeks invented with no Phoenician source.
  {
    letter: 'Φ', name: 'Phi', meaning: 'Greek invention — light / manifestation', gardiner: '',
    unicode: 0x00000, phoneme: 'pʰ (aspirated p → f)', greek: 'Φ phi', latin: 'F / Ph',
    hebrew: 'פ', arabic: 'ف', phoenician: '\u{10910}', scriptOnly: ['greek'],
    note: 'Phi (Φ) was invented by the Greeks to represent an aspirated P-sound that Semitic alphabets did not distinguish. Together with Chi (Χ) and Psi (Ψ), it was added to the end of the Western Greek alphabet as a cluster of "supplemental" letters the Phoenician system had no room for.',
    investigationHighlight: 'Phi is one of four letters that prove the Greek adaptation was creative, not just borrowing. Greeks took the Phoenician 22 and ADDED four more for sounds their language needed. Phi → Latin Ph → English "philosophy," "physics," "phone" — all the Ph-words in English are Greek-via-Phi. The aspirated P that Phoenician never wrote is the letter that gave Western civilization its vocabulary for ideas.',
    relatedNodes: ['alphabet-greek-vowel-revolution', 'alphabet-phoenician'],
  },
  {
    letter: 'Χ', name: 'Chi', meaning: 'Greek invention — ch / kh sound', gardiner: '',
    unicode: 0x00000, phoneme: 'kʰ (aspirated k)', greek: 'Χ chi', latin: 'Ch / X',
    hebrew: '(none)', arabic: 'خ', phoenician: '(none)', scriptOnly: ['greek'],
    note: 'Chi (Χ) was invented by the Greeks for the aspirated K sound. The Chi-Rho monogram (☧), the earliest Christian symbol, combines Χ and Ρ — the first two letters of ΧΡΙΣΤΟΣ (Christos). Emperor Constantine adopted it for his military standard in 312 CE.',
    investigationHighlight: 'Chi is the letter that became a symbol. The Chi-Rho ☧ — the earliest Christian monogram, Constantine\'s battle standard — is simply the first two letters of the Greek word for Christ. Chi looks like an X, which is why "Xmas" preserves the original Greek initial. The cross shape of Chi also echoes the ancient Taw (T/X), the last Hebrew letter and original mark of salvation — giving the Chi-Rho an unintended resonance 1,500 years deep.',
    relatedNodes: ['alphabet-greek-vowel-revolution', 'alphabet-coptic'],
  },
  {
    letter: 'Ψ', name: 'Psi', meaning: 'Greek invention — ps sound', gardiner: '',
    unicode: 0x00000, phoneme: 'ps', greek: 'Ψ psi', latin: 'Ps',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['greek'],
    note: 'Psi (Ψ) was invented for the "ps" cluster — a sound combination Greek needed but Phoenician had no dedicated sign for. Its trident shape suggests a Semitic influence but no direct Phoenician ancestor has been confirmed.',
    investigationHighlight: 'Psi is the symbol modern psychology chose for itself (the ψ icon in every psychology department). The choice is ironic: psi is the Greek letter for the sound-cluster "ps," but in the 19th century it was chosen as the initial of "psyche" (ψυχή, soul/mind). A letter invented for a phonological technicality became the emblem of the science of the mind — because the Greeks used the same word for soul and mind.',
    relatedNodes: ['alphabet-greek-vowel-revolution'],
  },
  {
    letter: 'Ω', name: 'Omega', meaning: 'great O — long vowel distinction', gardiner: 'D4',
    unicode: 0x13079, phoneme: 'ɔː (long o)', greek: 'Ω omega', latin: 'O',
    hebrew: 'ע', arabic: 'ع', phoenician: '\u{1090F}', scriptOnly: ['greek'],
    note: 'Omega (Ω) was invented by splitting the Omicron (O) into two letters: omicron ("small O," short vowel) and omega ("great O," long vowel). Greek distinguished vowel length where Phoenician did not. Omega is the last letter of the Greek alphabet — giving the "alpha and omega" formula its meaning.',
    investigationHighlight: '"I am the Alpha and the Omega" (Revelation 1:8) — the first and last letters of the Greek alphabet, meaning the beginning and the end. Omega was invented to distinguish short and long O sounds. Without the invention of Omega, the "alpha and omega" phrase — one of Christianity\'s foundational images of God — could not exist. A phonological distinction created a theological metaphor.',
    relatedNodes: ['alphabet-greek-vowel-revolution', 'alphabet-sefer-yetzirah'],
  },

  // ── Egyptian sacred signs (scriptOnly: ['hieroglyph']) ────────────────────
  // Major cosmological hieroglyphs beyond the 22 that became Phoenician letters.
  // These are the signs that make Egyptian hieroglyphs a sacred cosmological system.
  {
    letter: '𓋹', name: 'Ankh', meaning: 'life / immortality', gardiner: 'S34',
    unicode: 0x132F9, phoneme: 'ʿnḫ', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The Ankh — the looped cross — is the Egyptian sign for life and immortality. It appears in the hands of every deity. The crux ansata (Coptic cross) descends from the Ankh. The form may represent a sandal strap, a knot, or the union of male and female principles.',
    investigationHighlight: 'The Ankh is the most widely recognized Egyptian symbol in the modern world — worn, tattooed, and mass-produced globally. Early Christians in Egypt (the Coptic Church) adopted a modified Ankh as their cross form. This makes the Ankh one of the few pre-Christian symbols explicitly absorbed into Christian iconography with full awareness. The Coptic cross still carries the Ankh loop at its head in some traditions — a 5,000-year sacred sign surviving in a living church.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-coptic', 'alphabet-creation-by-word'],
  },
  {
    letter: '𓋔', name: 'Djed', meaning: 'stability / the spine of Osiris', gardiner: 'R11',
    unicode: 0x132BD, phoneme: 'ḏd', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The Djed pillar represents stability and the backbone of Osiris. The "raising of the Djed" ceremony on the last day of the month of Khoiak symbolized the resurrection of Osiris — the spine rising upright = the dead god returning to life. The Djed is one of the oldest Egyptian symbols, predating the Pharaonic period.',
    investigationHighlight: 'The Djed raising ceremony is one of the best-documented Egyptian rituals for the dying-and-rising god pattern. Osiris dies, his body is scattered, Isis reassembles it, and the raising of the Djed (his spine) marks his resurrection. This 5,000-year-old ritual is the Egyptian root of the dying-and-rising-god tradition that runs through Tammuz, Adonis, Dionysus, and Christ. The spine of a dead god becomes the pillar of the world.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word'],
  },
  {
    letter: '𓂀', name: 'Eye of Ra / Horus', meaning: 'divine sight / protection / royal power', gardiner: 'D4',
    unicode: 0x13079, phoneme: 'ir.t', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The Udjat — the Eye of Horus (or Ra) — is the most protective amulet in Egyptian tradition. The left eye of Horus was torn out by Set and restored by Thoth; the restored eye became the symbol of healing, protection, and royal authority. The eye fractions were used as a system of mathematical notation.',
    investigationHighlight: 'The Eye of Ra and Eye of Horus are the same symbol used in two contexts: Ra\'s eye is the sun itself (and the goddess Sekhmet/Hathor in her destructive aspect); Horus\'s restored eye is the moon. The eye fractions (½ + ¼ + ⅛ + 1/16 + 1/32 + 1/64 = 63/64) were used in medical prescriptions. Egyptian sacred geometry, medicine, and cosmology all ran through the same symbol. The Eye is also the origin of the Ayin (ע) → Omicron (O) transmission — the eye that became the letter O.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-isopsephy-greek'],
  },
  {
    letter: '𓆣', name: 'Scarab / Khepri', meaning: 'transformation / the rising sun / becoming', gardiner: 'L1',
    unicode: 0x131A3, phoneme: 'ḫpr', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The scarab beetle rolls its dung ball across the ground — and the Egyptians saw in this the sun god Khepri rolling the solar disk across the sky. The word ḫpr means "to become / to transform / to come into being." The scarab is the hieroglyph for becoming itself.',
    investigationHighlight: 'The scarab amulet is one of the most abundant archaeological artifacts from ancient Egypt and the ancient Mediterranean — found from Egypt to Britain to Afghanistan. Its meaning: transformation, rebirth, the sun rising again after the night of death. The dung beetle that lays its eggs in dead matter and from which new life emerges — Egyptians saw resurrection in an insect. Khepri the scarab is the dawn sun; Ra is the noon sun; Atum is the evening sun. One god, three scarab-transformation forms.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word'],
  },
  {
    letter: '𓆄', name: 'Feather of Maat', meaning: 'truth / justice / cosmic order', gardiner: 'H6',
    unicode: 0x13184, phoneme: 'mꜢʿt', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The single ostrich feather is Maat — the goddess of truth, justice, and cosmic order (maʿat). In the Hall of Two Truths, the dead person\'s heart was weighed against the feather of Maat on Anubis\'s scales. A heart heavier than the feather was devoured by Ammit. A heart light as a feather passed into eternity.',
    investigationHighlight: 'The Weighing of the Heart against the Feather of Maat — depicted in the Book of the Dead — is the oldest documented concept of divine judgment based on ethical conduct (c. 2400 BCE). The idea that the dead face a moral reckoning before a divine tribunal predates the Hebrew Bible\'s Judgment themes by 1,500–2,000 years. Egyptian Maat → Jewish Day of Judgment → Christian Last Judgment → Islamic Yawm al-Dīn: the cross-tradition pattern of weighing souls at death may originate with this single ostrich feather.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word'],
  },
  {
    letter: '𓇯', name: 'Solar Barque', meaning: 'the sun\'s journey through the underworld', gardiner: 'P3',
    unicode: 0x1329E, phoneme: '(determinative)', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'Ra crosses the sky in his solar barque by day and descends into the Duat (underworld) by night, battling Apep (the chaos serpent) in the 12 hours of darkness before rising again at dawn. The barque is the vehicle of cosmic continuity — the sun does not merely set; it fights for survival every night.',
    investigationHighlight: 'The solar barque cosmology is the Egyptian origin of the daily-battle-against-chaos narrative that underlies every dying-and-rising sun myth. Apep threatens Ra every night; Apep\'s defeat is why the sun rises. This nightly cosmic battle is one of the deepest layers of Western religious imagination — and one of the oldest, documented from c. 2400 BCE. The Psalms\' "pit" and "darkness"; the Harrowing of Hell; the Night Journey of Muhammad — all carry distant structural echoes of Ra\'s nightly passage.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word'],
  },
  {
    letter: '𓇸', name: 'Lotus', meaning: 'creation from the primordial waters', gardiner: 'M12',
    unicode: 0x131BC, phoneme: 'sfṯ / nḥb', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The lotus rises from the mud of the Nile and opens at dawn — Egyptians saw this as the primordial act of creation repeated daily. The first morning was a lotus opening on the surface of the primordial waters (Nun). The child sun god Nefertem emerges from the lotus. The lotus is the first thing to emerge from the chaos-water.',
    investigationHighlight: 'The lotus as symbol of enlightenment and spiritual emergence appears in Egyptian theology (c. 3000 BCE), Indian Buddhism (the Buddha on a lotus throne, c. 500 BCE), and Hindu cosmology (Brahma emerges from a lotus growing from Vishnu\'s navel). Three independent traditions, same image: the lotus rising from dark water as the emblem of consciousness emerging from matter. The Egyptian origin is documented; the transmission routes to India are debated but the structural parallel holds.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-brahmi-origin', 'alphabet-devanagari-sacred'],
  },
  {
    letter: '𓇳', name: 'Solar Disk (Ra)', meaning: 'the sun god — the supreme divine power', gardiner: 'N5',
    unicode: 0x131F3, phoneme: 'rꜤ', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The simple circle with a dot — or circle alone — is Ra, the sun, the supreme deity of much of Egyptian history. Akhenaten\'s religious revolution (c. 1353–1336 BCE) reduced all of Egyptian religion to this single disk: the Aten, the solar disk itself, with rays ending in hands.',
    investigationHighlight: 'Akhenaten\'s Aten theology is the most discussed candidate for proto-monotheism in the ancient world. Freud argued (Moses and Monotheism, 1939) that Moses was an Atenist priest whose theology survived Akhenaten\'s suppression and became the foundation of Israelite monotheism. The scholarly consensus rejects Freud\'s specific claim — but the structural parallel between Aten (one god, universal, no images) and early Yahwism (one god, universal, no images) remains one of the most contested questions in religious history. The solar disk is the center of the argument.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-sefer-yetzirah', 'alphabet-creation-by-word'],
  },

  // ── Egyptian hieroglyph expansion — soul, divine, cosmic, royal, scribal ──
  // 22 additional signs beyond the alphabetic chain and 8 sacred cosmological signs.
  // These are the signs that make hieroglyphs a complete theology, not just a script.

  // — Soul Trilogy (Ba · Ka · Akh) —
  {
    letter: '𓅡', name: 'Ba', meaning: 'the individual soul — the traveling self', gardiner: 'G29',
    unicode: 0x013161, phoneme: 'bꜣ', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The Ba is depicted as a human-headed bird — the aspect of the person that can fly between the world of the living and the dead. At night the Ba travels freely; by day it must return to the body. The Ba is not the whole soul; it is the personality, the individual character that persists after death.',
    investigationHighlight: 'Egypt had five components of the self: Ba (personality/traveling soul), Ka (vital double), Akh (luminous spirit), Ren (name), and Sheut (shadow). The Ba is closest to what the Greeks called psyche and the Hebrews called nefesh. The human-headed bird is the most precise image of what every tradition struggles to describe: the part of you that is distinctly you, that can leave the body, and that survives death. Three traditions, three words — one image from 3,000 BCE.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word', 'alphabet-sefer-yetzirah'],
  },
  {
    letter: '𓂓', name: 'Ka', meaning: 'the vital force — the spirit double', gardiner: 'D28',
    unicode: 0x013093, phoneme: 'kꜣ', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The Ka is shown as two upraised arms — the hieroglyph for the vital force or spirit double that accompanies every person from birth. The Ka stays with the body (and with the mummy) after death. To die in Egyptian was "to go to one\'s Ka." Offerings at the tomb were "for the Ka" — the vital force must be sustained.',
    investigationHighlight: 'The Ka is the Egyptian equivalent of what Sanskrit calls prana, Chinese qi, Hebrew ruah, Greek pneuma — the animating life-force that fills the body. Every tradition feels compelled to name it. The Egyptian version is the most architecturally specific: the Ka is a spirit double created at birth by the god Khnum on a potter\'s wheel alongside the body. Two identical forms made simultaneously — body and double — one mortal, one immortal. Khnum at the potter\'s wheel is the image Jeremiah borrows: "like clay in the hand of the potter."',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word'],
  },
  {
    letter: '𓅜', name: 'Akh', meaning: 'the luminous spirit — the transformed self', gardiner: 'G25',
    unicode: 0x01315C, phoneme: 'ꜣḫ', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The Akh is the crested ibis — the perfected, luminous soul that results from the successful union of Ba and Ka after death. An Akh is what an Egyptian hoped to become: a being of light dwelling in the Duat, capable of interceding in the world of the living. Malevolent spirits (called "akhu") are Akhs that failed to find peace.',
    investigationHighlight: 'The Akh is the Egyptian version of the enlightened/transformed soul — the self that has completed the death-journey and become luminous. The crested ibis was chosen because it was a migratory bird that appeared and disappeared — a visitor from another world. The root ꜣḫ means "to be effective, to shine." The same root appears in Akhet (the horizon, where the sun becomes Akh — shining). In the Pyramid Texts, the dead pharaoh becomes an Akh among the stars. The Hebrew malakh (angel/messenger, מלאך) and the Arabic malak share a root-structure that some scholars connect to the same luminous-being concept — the sent, shining one.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word', 'alphabet-greek-vowel-revolution'],
  },

  // — Divine Authority —
  {
    letter: '𓊹', name: 'Neter', meaning: 'god — the divine principle itself', gardiner: 'R8',
    unicode: 0x0132B9, phoneme: 'nṯr', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'Neter (𓊹) is the hieroglyph for "god" — a flag on a pole, representing the divine presence. Every Egyptian deity is a neter. The sign itself — a banner or standard — suggests that the divine is that which is elevated, visible, and rallies others toward it. The Egyptians had hundreds of neteru (gods); every neter was a facet of the one unknowable divine.',
    investigationHighlight: 'Neter is one of the most debated words in Egyptology. It means "god" but also "that which is renewed/refreshed" — the divine as perpetual renewal. Some scholars trace the word into Coptic (ntre) and suggest it influenced the Greek word for nature (natura via Latin). If that etymology holds, our word "nature" and the Egyptian word for "god" share a root: the divine IS the renewing force of the natural world. Egyptian polytheism and Western naturalism may be, terminologically, the same thing.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word', 'alphabet-coptic'],
  },
  {
    letter: '𓌀', name: 'Was Scepter', meaning: 'divine power and dominion', gardiner: 'S40',
    unicode: 0x013300, phoneme: 'wꜣs', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The Was scepter — a staff with an animal head (Set-animal or canine) at the top and a forked base — is the emblem of divine power. Every major deity holds it. Its name wꜣs means "power" or "dominion." The Was appears in the word for Thebes: Wꜣst — City of the Was, City of Power.',
    investigationHighlight: 'The Was, Djed, and Ankh form the three most common Egyptian power-objects: Was = dominion, Djed = stability, Ankh = life. Together they appear in the formula "all life, stability, and dominion" on temple walls — the three blessings the gods bestow on the pharaoh. This triad maps structurally onto many later three-part divine formulas: the Hindu trimurti (Brahma/Vishnu/Shiva = creation/preservation/destruction), the Christian Trinity, the Platonic Good/True/Beautiful. Three forces; one formula.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word'],
  },
  {
    letter: '𓌅', name: 'Flail', meaning: 'authority over the harvest — the striking power of the divine', gardiner: 'S45',
    unicode: 0x013305, phoneme: 'nḫꜣḫꜣ', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The flail (nḫꜣḫꜣ) is always paired with the crook (ḥqꜣ) in the hands of Osiris and the pharaoh. The crook gathers; the flail strikes. The crook is the shepherd gathering the flock; the flail is the thresher separating grain from chaff. Together they symbolize the complete cycle of pastoral and agricultural sovereignty.',
    investigationHighlight: 'The crook-and-flail is the most visually distinctive symbol of Egyptian royal theology. What is often missed: it is a grain-processing image. The crook = gathering (shepherd); the flail = threshing (farmer). The Pharaoh holds the tools of food production as symbols of divine kingship — sovereignty over the harvest IS sovereignty over life. This is the same theology behind the bread-and-wine eucharist: the substances that transform grain and grape into life-sustaining food become divine symbols. Osiris was murdered, dismembered, and his body scattered — like grain. He rose again. He IS the grain. The flail that threshes grain threshes the god.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word'],
  },

  // — Celestial and Cosmic Signs —
  {
    letter: '𓈌', name: 'Akhet', meaning: 'the horizon — where the sun becomes luminous', gardiner: 'N27',
    unicode: 0x01320C, phoneme: 'ꜣḫt', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'Akhet is the sun disk between two mountains — the horizon at sunrise or sunset. It is the liminal moment when the sun transitions between the worlds: underworld (Duat) and sky. The solar disk in the Akhet sign is the sun becoming Akh — luminous, transformed. The Akhet is the moment of resurrection repeated every morning.',
    investigationHighlight: 'The Akhet hieroglyph — sun between twin mountains — is the structural origin of the halo. The circle of light around divine heads in Christian, Buddhist, and Hindu iconography preserves the Egyptian sun-disk at the horizon. Akhenaten built his city Akhetaten (modern Amarna) at a location where the cliffs formed a natural Akhet shape at sunrise — the city was a living hieroglyph. Every morning the rising sun wrote the divine name in landscape. The East as the sacred direction of resurrection appears in Egyptian, Jewish (Jerusalem faces east), Christian (churches face east), and Islamic (facing Mecca, which from Egypt is roughly east) traditions — all orient toward the rising Akhet.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word'],
  },
  {
    letter: '𓇼', name: 'Duat Star', meaning: 'the underworld / the night sky / the starred abyss', gardiner: 'N14',
    unicode: 0x0131FC, phoneme: 'dwꜣt', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The five-pointed star is the sign for the Duat — the Egyptian underworld and night sky simultaneously. The Duat is not only underground; it is also above, among the stars. The dead travel to join the stars; the circumpolar stars that never set are the "imperishable ones," the souls of the blessed dead. The star-hieroglyph is also used to write "hour" (wnwt) — time is measured by stars.',
    investigationHighlight: 'The five-pointed star is over 5,000 years old as a sacred symbol — the Egyptian Duat sign. The same form appears as the Star of David (two triangles = Duat + inversion), the pentagram of Pythagoras (who spent 22 years in Egypt), the Seal of Solomon, and the stars on national flags worldwide. The Egyptians used the five-pointed star for the underworld because the stars are where the dead go. Every five-pointed star on every national flag is, etymologically, a sign for the land of the dead — the Duat, the starred abyss.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-isopsephy-greek', 'alphabet-creation-by-word'],
  },
  {
    letter: '𓅣', name: 'Bennu / Phoenix', meaning: 'the first life — resurrection from the primordial mound', gardiner: 'G31',
    unicode: 0x013163, phoneme: 'bnn', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The Bennu is the sacred heron of Heliopolis — the first living being to alight on the primordial mound (benben) at the moment of creation. The Bennu is the self-created bird, the manifestation of Ra-Osiris at the dawn of time. Greek travelers identified the Bennu with the Phoenix: the bird that dies and is reborn from its own ashes.',
    investigationHighlight: 'The Phoenix myth is Egyptian. Herodotus (c. 440 BCE) described seeing paintings of the "Phoenix" at Heliopolis — what he saw was the Bennu. The Bennu perches on the benben stone (the primordial mound, possibly the model for the pyramid capstone). The solar barque carries the Bennu at dawn. The word "benben" shares a root with "to arise, to shine forth." The Christian pelican feeding its young with its own blood is a medieval transformation of the same self-sacrificing resurrection-bird archetype. Five thousand years of the same image: the bird that is its own origin, that rises from its own end.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word'],
  },
  {
    letter: '𓇾', name: 'Primordial Mound', meaning: 'the first land — the point of creation', gardiner: 'N16',
    unicode: 0x0131FE, phoneme: 'tꜣ', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The primordial mound (benben or Nun-hill) is the first solid land to emerge from the primordial waters (Nun). All Egyptian creation accounts begin the same way: infinite, dark, still waters — then a mound emerges, and creation begins. This is also the determinative for "land" in Egyptian writing.',
    investigationHighlight: 'The emergence of land from primordial water is the most universal creation image in world religion. Egyptian: the benben mound rises from Nun. Hebrew: "the earth was without form, and darkness was over the face of the deep" — then dry land appears (Genesis 1:9). Sumerian: Eridu (the first city) = the first mound on the waters. Hindu: the cosmic tortoise rises from the ocean. The primordial mound is humanity\'s ur-image of beginning: matter organizing itself from chaos-water. Every temple in Egypt was built to model this mound — the sanctuary at the center is the high ground of creation, the spot where the world began.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word', 'alphabet-sefer-yetzirah'],
  },

  // — Deity Signs —
  {
    letter: '𓅃', name: 'Horus Falcon', meaning: 'the living sky — the divine king', gardiner: 'G5',
    unicode: 0x013143, phoneme: 'ḥr', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The Horus falcon is the sign of the living pharaoh, who is Horus incarnate. The sun is the right eye of Horus; the moon is his left eye (torn out by Set and restored by Thoth — hence the Eye of Horus as healing symbol). Horus defeats Set; the pharaoh as Horus defeats chaos. At death, the pharaoh becomes Osiris and his son becomes the new Horus.',
    investigationHighlight: 'The Horus/Osiris theology is the oldest clearly documented dying-and-rising-god sequence. Father (Osiris) is killed, dismembered, and reassembled; son (Horus) avenges the father and inherits the kingdom; the dead father rules the afterlife while the living son rules the earth. The structural parallel to the Christian Father/Son theology — God the Father, Christ the Son; Christ dies and rises; Christ reigns in heaven while the Church continues on earth — is either convergent evolution of a universal myth pattern, or direct transmission through Hellenistic Egyptian religion (which was deeply Christianized in Alexandria). The Horus falcon on the pharaoh\'s crown and the dove descending on Christ at baptism are both divine-bird-on-king images.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word'],
  },
  {
    letter: '𓅝', name: 'Thoth / Ibis', meaning: 'the scribe of the gods — inventor of writing', gardiner: 'G26',
    unicode: 0x01315D, phoneme: 'ḏḥwty', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'Thoth is the ibis-headed god of writing, knowledge, the moon, and magic. He invented hieroglyphs, recorded the Weighing of the Heart, and served as the scribe of the gods. He is also depicted as a baboon. The Greeks identified Thoth with Hermes — giving us Hermes Trismegistus ("thrice-great Hermes"), the legendary author of the Hermetic texts.',
    investigationHighlight: 'Thoth is the deity that bridges Egypt and Western occultism. The Greek identification of Thoth with Hermes produced Hermes Trismegistus — the legendary author attributed with the Corpus Hermeticum, the Emerald Tablet, and the Kybalion. The entire Western Hermetic tradition (alchemy, Kabbalah as filtered through Hermeticism, Rosicrucians, Freemasonry) claims descent from Thoth-Hermes. The ibis-god of scribes became, through this transmission, the patron saint of every Western esotericist. The Renaissance "Egyptian wisdom" craze (Ficino, Pico della Mirandola) was triggered by the re-discovery of the Corpus Hermeticum in 1460 — texts attributed to Thoth.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-isopsephy-greek', 'alphabet-creation-by-word'],
  },
  {
    letter: '𓃣', name: 'Anubis / Jackal', meaning: 'guardian of the dead — the weigher of hearts', gardiner: 'E16',
    unicode: 0x0130E3, phoneme: 'inpw', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'Anubis is the jackal-headed god of embalming, the guardian of the necropolis, and the guide of souls through the Duat. He oversees the Weighing of the Heart. The jackal was associated with death because jackals were seen scavenging near desert graveyards — the Egyptians incorporated the animal of death into the theology of death.',
    investigationHighlight: 'Anubis is the oldest psychopomp — the guide who leads souls from the world of the living to the world of the dead. The same role appears across traditions: Hermes Psychopompos (Greek), Mercury (Roman), Azrael (Islamic angel of death), the archangel Michael as weigher of souls. The jackal who guarded graves became the god who guards the transition itself. Anubis holds the scales in the Weighing of the Heart — he is both the embalmer who prepares the dead and the judge\'s assistant who keeps the balance honest. Every tradition that has a "guide of the dead" is, structurally, drawing on the same psychological need: the dying need a trusted figure who knows the way.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word'],
  },
  {
    letter: '𓁠', name: 'Shu', meaning: 'the atmosphere — the space between heaven and earth', gardiner: 'C4',
    unicode: 0x013060, phoneme: 'šw', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'Shu is the god of air and sunlight — the atmosphere itself, the space between the sky (Nut) and the earth (Geb). He is depicted as a man with an ostrich feather on his head, kneeling between the prone body of Geb (earth) and the arched body of Nut (sky), lifting Nut upward. Shu is the act of separation that makes life possible — without the space between sky and earth, there is no room for living things.',
    investigationHighlight: 'Shu separating Nut (sky) from Geb (earth) is the Egyptian creation act that produces the livable world. The same act appears in Genesis 1: "God separated the waters above from the waters below" (the firmament). In the Babylonian Enuma Elish, Marduk splits Tiamat in half — upper half becomes sky, lower half earth. The separation of primordial unity into sky and earth is the universal second act of creation (after "let there be light" or "mound from water"). Egyptian Shu is the divine embodiment of that separation — he IS the gap that makes space for life.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word'],
  },

  // — Royal and Protective Signs —
  {
    letter: '𓆗', name: 'Uraeus', meaning: 'the rearing cobra — royal divine protection', gardiner: 'I12',
    unicode: 0x013197, phoneme: 'jꜥrt', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The Uraeus is the rearing cobra on the pharaoh\'s crown — the divine protector that spits fire at the enemies of the king. It represents Wadjet, the cobra goddess of Lower Egypt. The Uraeus is the eye of Ra sent out into the world to destroy what threatens divine order. It is the serpent that burns — the destructive aspect of solar power in protective form.',
    investigationHighlight: 'The Uraeus — the risen serpent on the crown — is one of the most ancient images of divine serpent-power. The same concept appears in the Hindu kundalini (the coiled serpent at the base of the spine that rises to the crown, conferring divine power) and the Caduceus of Hermes (two serpents rising around a staff). The pharaoh who wears the Uraeus has the divine serpent-fire activated at the crown of the head — the same location and the same physiology as the kundalini crown chakra. The ancient world\'s most powerful king wears, at the top of his head, the image of the serpent that has risen.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word', 'alphabet-isopsephy-greek'],
  },
  {
    letter: '𓍷', name: 'Cartouche', meaning: 'the royal name sealed in eternity', gardiner: 'V10',
    unicode: 0x013377, phoneme: 'šnw', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The cartouche (šnw) is an oval loop enclosing the royal name. The shape is an extended Shen ring — a loop of rope with no end, symbolizing eternity. The pharaoh\'s name inside the cartouche is protected by eternal divine power. The name of a king without a cartouche was vulnerable; inside the oval, it was sealed.',
    investigationHighlight: 'The cartouche is the oldest form of the idea that a name has magical power and needs magical protection. The same concept appears in Jewish law: the divine name YHWH is so powerful it cannot be spoken, only written — and even the written form is treated with extreme reverence (Torah scrolls cannot be destroyed, only buried). In Islam, the divine names (99 names of Allah) are recited as protection. The Egyptian king\'s name in a cartouche, the Jewish divine name in a mezuzah, the Islamic basmala above a door — all are expressions of the same deep structure: sacred names sealed in protective containers ward off chaos.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-sefer-yetzirah', 'alphabet-creation-by-word'],
  },
  {
    letter: '𓍶', name: 'Shen Ring', meaning: 'eternity — the circle with no end', gardiner: 'V9',
    unicode: 0x013376, phoneme: 'šn', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The Shen is a loop of rope tied at the bottom with a bar — representing a circle with no beginning and no end. It is held by Horus falcons and Nekhbet vultures in their talons over the pharaoh as a sign of eternal protection. The Shen elongated became the cartouche; the Shen as a solar symbol connects to Ra\'s eternal circuit.',
    investigationHighlight: 'The Shen ring is the Egyptian eternity symbol — a loop of rope with no end. The ouroboros (the serpent eating its own tail, the most ancient Western symbol of eternity) is probably a zoomorphic version of the same idea: the Shen\'s circular rope = the serpent\'s circular body. The ouroboros appears first in Egyptian texts (the Enigmatic Book of the Netherworld, c. 1380 BCE), spreading to Greece via Alexandria and from there to the entire alchemical/Hermetic tradition. The circular "no-end" symbol of eternity enters every tradition that had contact with Egypt — and becomes, in alchemy, the symbol for the philosopher\'s stone: the thing that completes and closes the cycle.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word', 'alphabet-isopsephy-greek'],
  },
  {
    letter: '𓋖', name: 'Double Crown (Pschent)', meaning: 'unified sovereignty — the two lands as one', gardiner: 'S5',
    unicode: 0x0132D6, phoneme: 'sḫmty', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The Double Crown (Pschent) combines the White Crown of Upper Egypt (the tall conical crown) and the Red Crown of Lower Egypt (the flat-topped crown with a coil). Wearing the Pschent, the pharaoh rules the "Two Lands" — the unified Egypt. The unification of Upper and Lower Egypt c. 3100 BCE by Narmer is the founding act of the Egyptian state, commemorated in every double crown.',
    investigationHighlight: 'The Double Crown is political theology made into a hat. The pharaoh does not merely rule two regions; the pharaoh IS the union of two principles — the White Crown\'s Upper Egypt (the Nile Valley, the desert, the old kingdom, Osiris) and the Red Crown\'s Lower Egypt (the Delta, the sea, the new, Horus). The king\'s body holds together what would otherwise be two different worlds. This "sovereign as the union of opposites" theology runs from Egypt through every sacred king tradition: the Chinese Son of Heaven bridging heaven and earth, the Japanese Emperor as living kami, the medieval European king as the body of the nation. The double crown is the original image of the king as metaphysical hinge.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word'],
  },

  // — Scribal and Sacred Object Signs —
  {
    letter: '𓏞', name: 'Scribal Palette', meaning: 'writing as divine act — the scribe\'s sacred tools', gardiner: 'Y3',
    unicode: 0x0133DE, phoneme: 'mnḥd', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The scribal palette (a rectangular board with two ink-cakes — one black, one red — and a slot for reed pens) is the determinative for "writing" in Egyptian. Every scribe carried one. It was placed in tombs as an offering. The scribe\'s tools were sacred objects: to write hieroglyphs was to participate in the creative act of the gods, since Thoth had invented the script.',
    investigationHighlight: 'In Egypt, only about 1% of the population was literate. Scribes were a priestly class. The hieroglyphic script was called medu netjer — "words of god" — and to write it was a sacred act. The scribal palette in a tomb equipped the dead for writing in the afterlife, because the Duat required the same bureaucracy as the living world (accounts, records, the Book of the Dead itself). The idea that writing connects the human to the divine — that literacy is a form of spiritual access — appears in every tradition that has a sacred scripture: the Torah (written by God at Sinai), the Quran (dictated by Gabriel), the Vedas (heard, not composed). Egypt is the oldest clear case: writing was invented by a god and scribes were his deputies.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word', 'alphabet-arabic-quran'],
  },
  {
    letter: '𓏛', name: 'Papyrus Scroll', meaning: 'knowledge — the sealed record of divine wisdom', gardiner: 'Y1',
    unicode: 0x0133DB, phoneme: 'mḏꜣt', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The sealed papyrus roll is the determinative for "book," "writing," and "abstract concepts" in Egyptian. Any word referring to an intangible idea — knowledge, wisdom, art — is written with this sign. The scroll is the container of meaning; the sealed roll is meaning held and protected.',
    investigationHighlight: 'The papyrus scroll as the vessel of sacred knowledge appears at the foundation of every book-religion. Egypt exported papyrus to the entire ancient world — the word "papyrus" gives us "paper." The Phoenicians brought the Egyptian scroll technology to Greece; the Greeks called their writing material byblos (from the Phoenician city Byblos, the papyrus trade hub) — which gives us "Bible." The Hebrew word sefer (book/scroll, ספר), Arabic mushaf (Quran manuscript), Greek biblos — all the sacred book words trace to Egyptian papyrus technology. The scroll that holds the word of God is an Egyptian invention, literally.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-phoenician', 'alphabet-creation-by-word'],
  },
  {
    letter: '𓊮', name: 'Flame', meaning: 'purification — the fire that transforms', gardiner: 'Q7',
    unicode: 0x0132AE, phoneme: 'ḫt / sḏt', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The flame determinative appears in Egyptian for words meaning fire, heat, burning, and purification. In Egyptian theology, fire has a dual role: it destroys the enemies of Ra in the Duat (the Lake of Fire), and it purifies and illuminates. The sacred flame of the temples burned continuously.',
    investigationHighlight: 'The Lake of Fire in the Egyptian Book of the Dead (where the unjudged hearts are destroyed) is the direct ancestor of the concept of hell in Abrahamic traditions. The term "lake of fire" appears verbatim in Revelation (20:10, 20:14-15) — one of the most explicit textual continuities between Egyptian afterlife theology and Christian eschatology. Egyptian fire purifies or destroys depending on the moral state of what it touches — the same ambivalence appears in the Zoroastrian final judgment (all souls pass through a river of fire: for the righteous it is warm milk; for the wicked it is burning). Fire as the final moral discriminator is an Egyptian theological export.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word'],
  },
  {
    letter: '𓏣', name: 'Sistrum', meaning: 'the divine rattle — music as cosmic vibration', gardiner: 'Y8',
    unicode: 0x0133E3, phoneme: 'sššt', greek: '(none)', latin: '(none)',
    hebrew: '(none)', arabic: '(none)', phoenician: '(none)', scriptOnly: ['hieroglyph'],
    note: 'The sistrum is the sacred rattle of the goddess Hathor — shaken in ritual to please the gods and ward off chaos. The rattle\'s sound represented the rustling of papyrus reeds in the Nile wind. Sistrum-players accompanied every major temple ritual. When the sistrum is shaken, the universe is reminded to stay in order.',
    investigationHighlight: 'The sistrum connects Egypt to the oldest layer of musical theology: sound as the tool for maintaining cosmic order. The Egyptian belief that ritual music prevents chaos (the sistrum holds Apophis at bay) appears in the Vedic understanding that proper chanting (mantra) maintains the cosmic order (rta), in the Pythagorean belief that the harmony of the spheres must be mirrored by earthly music, and in the Jewish temple\'s Levitical choir (whose silence would have been catastrophic). Every culture that has sacred music believes the same thing: the universe requires sound to continue. The sistrum is the instrument that shakes chaos back into order.',
    relatedNodes: ['alphabet-medu-netjer', 'alphabet-creation-by-word'],
  },

  // ── Arabic-only additions (scriptOnly: ['arabic']) ────────────────────────
  // 6 letters Arabic developed beyond the 22 Phoenician base.
  // Arabic reached 28 letters; these 6 have no direct Phoenician ancestor.
  {
    letter: 'ث', name: 'Tha', meaning: 'emphatic th — Arabic sound expansion', gardiner: '',
    unicode: 0x062B, phoneme: 'θ (voiced → ث)', greek: '(none)', latin: 'Th',
    hebrew: '(none)', arabic: 'ث', phoenician: '(none)', scriptOnly: ['arabic'],
    note: 'Tha (ث) represents the voiceless dental fricative — the "th" in "think." It was added to the Arabic script by placing dots above the base letter Sin (ث = ش with different dots). The dot-diacritic system let Arabic create six new letters from existing forms without inventing new shapes.',
    investigationHighlight: 'The Arabic dot system is one of the most elegant expansions of an alphabet in history. Arabic took 17 basic letterforms from the 22 Phoenician letters and generated 28 distinct letters by adding 1, 2, or 3 dots above or below. Six letters (ث خ ذ ض ظ غ) have no Phoenician root — they represent sounds Semitic scribes needed for Arabic phonology but which the original abjad never encoded. The dots are not decoration; they are a complete phonological expansion system built onto a 3,000-year-old chassis.',
    relatedNodes: ['alphabet-arabic-quran', 'alphabet-phoenician'],
  },
  {
    letter: 'خ', name: 'Kha', meaning: 'guttural kh — the divine breath consonant', gardiner: '',
    unicode: 0x062E, phoneme: 'x / χ (velar fricative)', greek: '(none)', latin: 'Kh',
    hebrew: 'כ/ח', arabic: 'خ', phoenician: '(none)', scriptOnly: ['arabic'],
    note: 'Kha (خ) is the voiceless velar fricative — the sound in Scottish "loch" or German "Bach." It is formed by placing a dot above Ha (ح). In Arabic, Kha appears in the divine name "al-Khāliq" (the Creator) and in "khayr" (goodness). The sound has no English equivalent.',
    investigationHighlight: 'Kha shares its place in the divine vocabulary of Arabic with Ha and Kaf — all three are used in divine epithets. "al-Khāliq" (the Creator), "al-Ḥaqq" (the Truth), "al-Kabīr" (the Great). The guttural consonants of Arabic are not roughness; they are precision — sounds that distinguish meanings that lighter consonants would conflate. The Quran\'s untranslatability is partly a consonant problem: the English alphabet cannot render Kha, ʿAyn, Ḥa, or Ghain, so every transliteration loses phonological precision that the original text encodes.',
    relatedNodes: ['alphabet-arabic-quran', 'alphabet-quran-sacred-language'],
  },
  {
    letter: 'ذ', name: 'Dhal', meaning: 'voiced th — the sound of "this"', gardiner: '',
    unicode: 0x0630, phoneme: 'ð (voiced dental fricative)', greek: '(none)', latin: 'Dh',
    hebrew: '(none)', arabic: 'ذ', phoenician: '(none)', scriptOnly: ['arabic'],
    note: 'Dhal (ذ) is the voiced dental fricative — the "th" in "this" (not "think"). It is Dal (د) with a dot. The Arabic script distinguishes what English cannot: "this" (ð) and "think" (θ) are written with completely different letters (ذ and ث) — the dot marks the voicing distinction that English "th" erases.',
    investigationHighlight: 'Arabic makes phonological distinctions English cannot. Tha (ث) vs Dhal (ذ) = "think" vs "this" — unvoiced vs voiced, two completely separate letters. Sin (س) vs Sad (ص) = plain s vs emphatic s. Dal (د) vs Dad (ض) = plain d vs emphatic d. The Arabic consonant grid is more precise than English in the same way that a 28-color palette is more precise than a 22-color palette. The "difficulty" of Arabic to Western learners is largely a precision problem: Arabic distinguishes what European languages collapsed into single sounds.',
    relatedNodes: ['alphabet-arabic-quran', 'alphabet-phoenician'],
  },
  {
    letter: 'ض', name: 'Dad', meaning: 'emphatic d — the letter Arabic is named for', gardiner: '',
    unicode: 0x0636, phoneme: 'dˤ (pharyngealized d)', greek: '(none)', latin: 'D',
    hebrew: '(none)', arabic: 'ض', phoenician: '(none)', scriptOnly: ['arabic'],
    note: 'Dad (ض) is the emphatic or pharyngealized D — pronounced with the back of the tongue raised toward the pharynx, giving a "dark" quality to the surrounding vowels. Classical Arabic was so distinguished by this sound that the language was called "Lughat al-Dad" — the language of the Dad. No other language in the world has this specific phoneme.',
    investigationHighlight: 'Arabic is the only language in the world with the Dad phoneme — a pharyngealized D that no other human language has developed independently. The Arabs called their own language "Lughat al-Dad" (the language of the ض) as early as the 8th century. The Quran\'s opening chapter uses Dad in "al-Ḍāllīn" (those who are astray) — the very first Sura ends on a letter unique to Arabic on Earth. The uniqueness of this phoneme was historically used as theological evidence that Arabic was a divinely chosen language.',
    relatedNodes: ['alphabet-arabic-quran', 'alphabet-quran-sacred-language'],
  },
  {
    letter: 'ظ', name: 'Dha', meaning: 'emphatic dh — pharyngealized voiced th', gardiner: '',
    unicode: 0x0638, phoneme: 'ðˤ (pharyngealized voiced dental fricative)', greek: '(none)', latin: 'Dh',
    hebrew: '(none)', arabic: 'ظ', phoenician: '(none)', scriptOnly: ['arabic'],
    note: 'Dha (ظ) is the pharyngealized form of Dhal (ذ) — a voiced dental fricative with dark pharyngeal coloring. It is one of the four "emphatic" consonants in Arabic (ص ض ط ظ). The emphatics are the hardest Arabic sounds for non-native speakers and are the primary source of vowel darkening (imala) in Classical Arabic phonology.',
    investigationHighlight: 'The four Arabic emphatic consonants (ص ض ط ظ) represent a systematic phonological category with no parallel in any European language. They are not just "harder" versions of their plain counterparts — they trigger completely different vowel qualities in the surrounding syllables. When the Quran describes itself as "Arabic mubīn" (clear Arabic), it means this precision: Arabic has consonants that other languages lack, and those consonants carry semantic distinctions that translation cannot preserve. The emphatics are the consonantal infrastructure of untranslatability.',
    relatedNodes: ['alphabet-arabic-quran', 'alphabet-quran-sacred-language'],
  },
  {
    letter: 'غ', name: 'Ghain', meaning: 'voiced guttural — the sound of depth', gardiner: '',
    unicode: 0x063A, phoneme: 'ɣ (voiced velar fricative)', greek: '(none)', latin: 'Gh',
    hebrew: '(none)', arabic: 'غ', phoenician: '(none)', scriptOnly: ['arabic'],
    note: 'Ghain (غ) is the voiced velar fricative — roughly the sound of gargling, or the French R. It is Ayn (ع) with a dot, but they are entirely different phonemes: Ayn is a pharyngeal constriction, Ghain is a velar fricative. In the word "Ghayb" — the unseen, the hidden, the divine mystery — Ghain carries the sound of what cannot be seen.',
    investigationHighlight: 'The Arabic word "al-Ghayb" (الغيب) — the unseen, the hidden realm, the divine mystery — is built on Ghain, a letter with no English equivalent. The Quran declares that only Allah knows the Ghayb (6:59, 27:65). Ghain begins the word that names the boundary between the knowable and the unknowable. The letter that describes the hidden divine uses a sound that most of humanity\'s languages cannot make. The phonological boundary and the theological boundary coincide: what cannot be pronounced cannot be fully known.',
    relatedNodes: ['alphabet-arabic-quran', 'alphabet-quran-sacred-language'],
  },
];

// Gematria / Isopsephy / Abjad comparative data
// 22 Hebrew letters with their numeric values across three traditions
window.ALPHA_GEMATRIA = [
  { heb: 'א', name: 'Aleph',  val: 1,   greek: 'Α', gName: 'Alpha',  greekVal: 1,   arabic: 'ا', aName: 'Alif',   arabicVal: 1   },
  { heb: 'ב', name: 'Beth',   val: 2,   greek: 'Β', gName: 'Beta',   greekVal: 2,   arabic: 'ب', aName: 'Ba',     arabicVal: 2   },
  { heb: 'ג', name: 'Gimel',  val: 3,   greek: 'Γ', gName: 'Gamma',  greekVal: 3,   arabic: 'ج', aName: 'Jim',    arabicVal: 3   },
  { heb: 'ד', name: 'Daleth', val: 4,   greek: 'Δ', gName: 'Delta',  greekVal: 4,   arabic: 'د', aName: 'Dal',    arabicVal: 4   },
  { heb: 'ה', name: 'He',     val: 5,   greek: 'Ε', gName: 'Epsilon',greekVal: 5,   arabic: 'ه', aName: 'Ha',     arabicVal: 5   },
  { heb: 'ו', name: 'Vav',    val: 6,   greek: 'Ϝ', gName: 'Digamma',greekVal: 6,   arabic: 'و', aName: 'Waw',    arabicVal: 6   },
  { heb: 'ז', name: 'Zayin',  val: 7,   greek: 'Ζ', gName: 'Zeta',   greekVal: 7,   arabic: 'ز', aName: 'Zayn',   arabicVal: 7   },
  { heb: 'ח', name: 'Heth',   val: 8,   greek: 'Η', gName: 'Eta',    greekVal: 8,   arabic: 'ح', aName: 'Ha',     arabicVal: 8   },
  { heb: 'ט', name: 'Teth',   val: 9,   greek: 'Θ', gName: 'Theta',  greekVal: 9,   arabic: 'ط', aName: 'Ta',     arabicVal: 9   },
  { heb: 'י', name: 'Yod',    val: 10,  greek: 'Ι', gName: 'Iota',   greekVal: 10,  arabic: 'ي', aName: 'Ya',     arabicVal: 10  },
  { heb: 'כ', name: 'Kaph',   val: 20,  greek: 'Κ', gName: 'Kappa',  greekVal: 20,  arabic: 'ك', aName: 'Kaf',    arabicVal: 20  },
  { heb: 'ל', name: 'Lamed',  val: 30,  greek: 'Λ', gName: 'Lambda', greekVal: 30,  arabic: 'ل', aName: 'Lam',    arabicVal: 30  },
  { heb: 'מ', name: 'Mem',    val: 40,  greek: 'Μ', gName: 'Mu',     greekVal: 40,  arabic: 'م', aName: 'Mim',    arabicVal: 40  },
  { heb: 'נ', name: 'Nun',    val: 50,  greek: 'Ν', gName: 'Nu',     greekVal: 50,  arabic: 'ن', aName: 'Nun',    arabicVal: 50  },
  { heb: 'ס', name: 'Samekh', val: 60,  greek: 'Ξ', gName: 'Xi',     greekVal: 60,  arabic: 'س', aName: 'Sin',    arabicVal: 60  },
  { heb: 'ע', name: 'Ayin',   val: 70,  greek: 'Ο', gName: 'Omicron',greekVal: 70,  arabic: 'ع', aName: 'Ayn',    arabicVal: 70  },
  { heb: 'פ', name: 'Pe',     val: 80,  greek: 'Π', gName: 'Pi',     greekVal: 80,  arabic: 'ف', aName: 'Fa',     arabicVal: 80  },
  { heb: 'צ', name: 'Tsade',  val: 90,  greek: 'Ϙ', gName: 'Qoppa',  greekVal: 90,  arabic: 'ص', aName: 'Sad',    arabicVal: 90  },
  { heb: 'ק', name: 'Qoph',   val: 100, greek: 'Ρ', gName: 'Rho',    greekVal: 100, arabic: 'ق', aName: 'Qaf',    arabicVal: 100 },
  { heb: 'ר', name: 'Resh',   val: 200, greek: 'Σ', gName: 'Sigma',  greekVal: 200, arabic: 'ر', aName: 'Ra',     arabicVal: 200 },
  { heb: 'ש', name: 'Shin',   val: 300, greek: 'Τ', gName: 'Tau',    greekVal: 300, arabic: 'ش', aName: 'Shin',   arabicVal: 300 },
  { heb: 'ת', name: 'Tav',    val: 400, greek: 'Υ', gName: 'Upsilon',greekVal: 400, arabic: 'ت', aName: 'Ta',     arabicVal: 400 },
];
