#!/bin/bash
# Concatenate the forge/*.js carved modules into one bundle file.
#
# Phase 23.1-bundle (2026-05-25 NIGHT) — eliminates the per-module
# boot cost of separate <script> tags + IIFE invocations.
#
# Each module is a self-contained IIFE that registers window._forgeFoo.
# They have no inter-module dependencies (each only depends on forge.js
# scope via the attach({...deps}) call from forge.js). So load order
# doesn't matter — but we keep them in carve-phase order for
# readability of the bundle file.
#
# Phase scripture-mode step 3 (2026-05-28) — added scripture-reader.js
# (overlay window for sacred-text reading; step 3 of 7 in
# AUDIT/2026-05-28-scripture-mode-spec.md).
#
# USAGE: ./scripts/build-forge-bundle.sh
# OUTPUT: src/js/forge/_bundle.js
#
# Re-run after editing any individual module to regenerate the bundle.

set -e
cd "$(dirname "$0")/.."

OUT=src/js/forge/_bundle.js
MODULES=(
  src/js/forge/timeline-scrubber.js
  src/js/forge/legend.js
  src/js/forge/fx-panel.js
  src/js/forge/style-panel.js
  src/js/forge/search-autocomplete.js
  src/js/forge/hover-card.js
  src/js/forge/side-panel.js
  src/js/forge/debug-stats.js
  src/js/forge/view-settings.js
  src/js/forge/scripture-reader.js
  src/js/forge/codex-controls.js
  src/js/forge/ground.js
  src/js/forge/lab-panel.js
  src/js/forge/install-public-api.js
)

{
  echo "// ============================================================"
  echo "// CODEX ATLAS — FORGE MODULE BUNDLE (auto-generated)"
  echo "// ============================================================"
  echo "//"
  echo "// Generated by scripts/build-forge-bundle.sh — DO NOT EDIT BY HAND."
  echo "// Concatenation of carved Forge sub-modules (Phase 23.1 a-j +"
  echo "// scripture-mode step 3)."
  echo "//"
  echo "// To regenerate: ./scripts/build-forge-bundle.sh"
  echo "// To edit a module: edit the source file in src/js/forge/, then re-run."
  echo "// ============================================================"
  echo ""
  for m in "${MODULES[@]}"; do
    echo "// ─── $m ──────────────────────────────"
    cat "$m"
    echo ""
  done
} > "$OUT"

LOC=$(wc -l < "$OUT")
echo "Wrote $OUT ($LOC lines, $(echo "${#MODULES[@]}") modules concatenated)"
