#!/usr/bin/env python3
"""
Regenerate src/data/boards-library.js from 00_meta/MASSIVE-WINS-INDEX.md.

Run after editing the MASSIVE-WINS-INDEX so the BOARDS V2 Investigation
Library (step 5) stays in sync with the documented spines.
"""
import re, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, '00_meta/MASSIVE-WINS-INDEX.md')
DST  = os.path.join(ROOT, 'src/data/boards-library.js')

text = open(SRC).read()
current_label = None
section_breaks = {}
for line in text.split('\n'):
    m = re.match(r'^## (.+?)$', line)
    if m: current_label = m.group(1).strip()
    m = re.match(r'^### (\d+)\. ', line)
    if m: section_breaks[int(m.group(1))] = current_label

chunks = re.split(r'\n### (\d+)\. ([^\n]+)\n', text)
entries = []
for i in range(1, len(chunks)-2, 3):
    num = int(chunks[i]); title = chunks[i+1].strip(); body = chunks[i+2]
    m = re.search(r'Nodes:\s*(.+?)(?:\n\n|\Z)', body, re.DOTALL)
    if not m: continue
    picks = re.findall(r'\[\[([^\]]+)\]\]', m.group(1))
    first = next((l for l in body.split('\n') if l.strip()), '')
    headline = first.strip('*').strip()
    entries.append({
        'id': f'mw-{num:03d}', 'num': num, 'name': title,
        'headline': headline[:200], 'picks': picks,
        'section': section_breaks.get(num, ''),
    })

transmissions = [e for e in entries if 'TRANSMISSION' in (e['section'] or '').upper()]
massive_wins  = [e for e in entries if 'TRANSMISSION' not in (e['section'] or '').upper()]

def js_str(s): return "'" + s.replace('\\','\\\\').replace("'","\\'") + "'"

with open(DST, 'w') as out:
    out.write('// ============================================================\n')
    out.write('// CODEX ATLAS — BOARDS V2 Investigation Library (step 5)\n')
    out.write('// ============================================================\n')
    out.write('//\n')
    out.write('// GENERATED from 00_meta/MASSIVE-WINS-INDEX.md by\n')
    out.write('// scripts/build-boards-library.py. Re-run after editing the\n')
    out.write('// index file. Do NOT edit this file by hand.\n')
    out.write('// ============================================================\n')
    out.write('(function () {\n')
    out.write("  'use strict';\n\n")
    out.write('  const MASSIVE_WINS_BOARDS = [\n')
    for e in massive_wins:
        out.write('    {\n')
        out.write(f"      id: {js_str(e['id'])},\n")
        out.write(f"      name: {js_str(str(e['num']) + '. ' + e['name'])},\n")
        out.write(f"      headline: {js_str(e['headline'])},\n")
        out.write(f"      picks: [{', '.join(js_str(p) for p in e['picks'])}],\n")
        out.write('    },\n')
    out.write('  ];\n\n')
    out.write('  const TRANSMISSIONS_BOARDS = [\n')
    for e in transmissions:
        out.write('    {\n')
        out.write(f"      id: {js_str(e['id'])},\n")
        out.write(f"      name: {js_str(str(e['num']) + '. ' + e['name'])},\n")
        out.write(f"      headline: {js_str(e['headline'])},\n")
        out.write(f"      picks: [{', '.join(js_str(p) for p in e['picks'])}],\n")
        out.write('    },\n')
    out.write('  ];\n\n')
    out.write('  window.BOARDS_LIBRARY = {\n')
    out.write('    massiveWins:   MASSIVE_WINS_BOARDS,\n')
    out.write('    transmissions: TRANSMISSIONS_BOARDS,\n')
    out.write('  };\n')
    out.write('})();\n')

print(f'Wrote {DST}')
print(f'  {len(massive_wins)} MASSIVE WINS + {len(transmissions)} TRANSMISSIONS')
