#!/usr/bin/env python3
"""
dashboard_audit_summary.py — surface AUDIT/ state for the DASHBOARD.

Scans `AUDIT/**/*.md` and prints a summary that can be embedded in
`00_meta/DASHBOARD.md` (or read by any future tooling) so audit
findings stop becoming a write-only graveyard. Closes TYRANT
remediation finding P1 #10.

Output sections:
  - Total audit docs + recent (last 7 days)
  - Unchecked action items (`- [ ]`) per doc, sorted by count desc
  - Recently-shipped audits (lines containing "shipped", "FINISHED",
    "✅", "applied")

Stdlib only.

Usage:
    python3 scripts/dashboard_audit_summary.py            # human-readable to stdout
    python3 scripts/dashboard_audit_summary.py --markdown # emit a markdown block
    python3 scripts/dashboard_audit_summary.py --write    # update DASHBOARD.md in place
"""
import argparse
import datetime
import re
import sys
from pathlib import Path

VAULT = Path(__file__).resolve().parent.parent
AUDIT_DIR = VAULT / "AUDIT"
DASHBOARD = VAULT / "00_meta" / "DASHBOARD.md"
MARKER_BEGIN = "<!-- TYRANT-AUDIT-SUMMARY:BEGIN -->"
MARKER_END   = "<!-- TYRANT-AUDIT-SUMMARY:END -->"

UNCHECKED_RE = re.compile(r"^\s*-\s*\[\s\]\s+", re.MULTILINE)
SHIPPED_RE   = re.compile(r"(shipped|FINISHED|applied|✅|locked)", re.IGNORECASE)


def collect():
    docs = sorted(AUDIT_DIR.glob("*.md"))
    now = datetime.datetime.now()
    week_ago = now - datetime.timedelta(days=7)
    items = []
    for p in docs:
        try:
            text = p.read_text(encoding="utf-8")
        except Exception:
            continue
        unchecked = len(UNCHECKED_RE.findall(text))
        mtime = datetime.datetime.fromtimestamp(p.stat().st_mtime)
        recent = mtime >= week_ago
        shipped = bool(SHIPPED_RE.search(text[:2000]))
        items.append({
            "path":      p.relative_to(VAULT).as_posix(),
            "unchecked": unchecked,
            "mtime":     mtime,
            "recent":    recent,
            "shipped":   shipped,
        })
    return items


def render_markdown(items):
    total = len(items)
    recent = sum(1 for i in items if i["recent"])
    shipped = sum(1 for i in items if i["shipped"])
    total_open = sum(i["unchecked"] for i in items)
    lines = []
    lines.append("**Audit summary** (auto-generated by `scripts/dashboard_audit_summary.py`)")
    lines.append("")
    lines.append(f"- **{total}** audit docs total; **{recent}** in the last 7 days; **{shipped}** marked shipped/finished/applied.")
    lines.append(f"- **{total_open}** unchecked action items across the folder (live work queue).")
    lines.append("")
    lines.append("**Top 10 docs by open action-item count:**")
    lines.append("")
    top = sorted([i for i in items if i["unchecked"] > 0],
                 key=lambda x: -x["unchecked"])[:10]
    if not top:
        lines.append("- (no open action items found)")
    else:
        for i in top:
            mark = "✅" if i["shipped"] else "🔧"
            lines.append(f"- {mark} `{i['path']}` — **{i['unchecked']}** open")
    lines.append("")
    lines.append(f"_Snapshot: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')} — re-run `scripts/dashboard_audit_summary.py` to refresh._")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--markdown", action="store_true",
                    help="Emit markdown to stdout (between the BEGIN/END markers).")
    ap.add_argument("--write", action="store_true",
                    help="Update 00_meta/DASHBOARD.md in place between the markers.")
    args = ap.parse_args()

    items = collect()
    md = render_markdown(items)

    if args.write:
        if not DASHBOARD.exists():
            print(f"[dashboard_audit_summary] {DASHBOARD} does not exist; nothing to update.")
            return 1
        text = DASHBOARD.read_text(encoding="utf-8")
        if MARKER_BEGIN in text and MARKER_END in text:
            before = text.split(MARKER_BEGIN, 1)[0]
            after  = text.split(MARKER_END, 1)[1]
            new_text = before + MARKER_BEGIN + "\n" + md + "\n" + MARKER_END + after
        else:
            # Append at end.
            new_text = text.rstrip() + "\n\n" + MARKER_BEGIN + "\n" + md + "\n" + MARKER_END + "\n"
        DASHBOARD.write_text(new_text, encoding="utf-8")
        print(f"[dashboard_audit_summary] updated {DASHBOARD.relative_to(VAULT)}")
        return 0

    if args.markdown:
        print(MARKER_BEGIN)
        print(md)
        print(MARKER_END)
        return 0

    # Default: human-readable summary.
    print(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
